// ── A COPY. DO NOT EDIT THIS FILE. ─────────────────────────────────────────
//
// Source: webapp/lib/workout/buildAsYouGo.ts
//
// NP-058 applying NP-017: the training, streak and dashboard logic is pure,
// so both apps run the SAME code instead of two implementations of it. A
// behaviour change lands on the WEB first and is re-copied here, and
// webapp/tests/unit/nativeParity/trainingModules.test.ts runs this copy
// against the web source over a fixture table and fails until it is.
// Re-copy procedure: expo/README.md, "Re-copying a training module".
//
// The only edits a copy may carry:
//  * imports rewritten to relative paths, and the webapp model/store types
//    they were type-only imports of mirrored in ../types.ts;
//  * the non-null assertions `noUncheckedIndexedAccess` asks for (set by
//    expo/tsconfig.json, which typechecks these sources; webapp does not
//    set it). Assertions only — no runtime branch is added or removed.
// ──────────────────────────────────────────────────────────────────────────
// Build as you go — add exercises to a workout that is already running, and
// turn what is already there into a superset or a circuit, mid-session.
//
// A session used to be fixed the moment you started it: whatever you picked in
// the builder was the whole workout, and finding the next machine free meant
// finishing early or abandoning the log. These helpers let the live view, the
// track view and the session editor all add, group and ungroup with the same
// rules, so the three never disagree about what the workout is.
//
// Two invariants the rest of the code leans on:
//
//   1. `groupExercises` in lib/workoutUtils only groups CONSECUTIVE exercises
//      sharing a groupId. So grouping has to physically move exercises next to
//      each other — hence every mutation returns an `order` (old index per new
//      position) that callers use to permute their parallel arrays (set data,
//      swaps, per-exercise progress).
//   2. Nothing here touches React, the DOM, or Mongo. Pure in, pure out.

import type { WorkoutExercise } from '../workoutUtils'

/** The group kinds a member can create from inside a session. */
export type GroupKind = 'superset' | 'circuit' | 'triset' | 'giant_set'

export interface AdHocExercise extends WorkoutExercise {
  /** Added during the session rather than programmed / drafted up front. */
  addedAdHoc?: boolean
}

/**
 * The only fields the list mutations read or write. A mutation is generic over
 * any exercise row that carries the group fields (the native live session's
 * `LiveWorkoutExercise` does, but types `videoUrl` / `trackingType` as nullable,
 * so it is not assignable to the full `WorkoutExercise`).
 */
export type GroupableExercise = Pick<
  WorkoutExercise,
  'name' | 'sets' | 'groupId' | 'groupType' | 'groupLabel' | 'groupRest' | 'groupRounds'
>

/** The result of any mutation: the new list plus how the old one maps onto it. */
export interface MutationResult<T extends GroupableExercise> {
  exercises: T[]
  /** `order[newIndex] = oldIndex`, or -1 for an exercise that did not exist before. */
  order: number[]
}

export const GROUP_KINDS: GroupKind[] = ['superset', 'circuit', 'triset', 'giant_set']

/** What a brand-new exercise gets when nothing in the session suggests better. */
export const DEFAULT_SETS = 3

/**
 * The set count a newly added exercise should start on.
 *
 * It used to be a flat 3 everywhere, so adding an exercise to a five-set
 * session produced a workout that disagreed with itself before the member had
 * touched anything. The FIRST exercise is the one the session was built
 * around, so a new one starts on its count. Still only a default: changing it
 * by hand changes it.
 */
export function defaultSetsFor(list: Pick<WorkoutExercise, 'sets'>[]): number {
  const first = list[0]?.sets
  return typeof first === 'number' && first > 0 ? Math.max(1, Math.floor(first)) : DEFAULT_SETS
}

/**
 * Whether a group of this kind runs every member for the same number of
 * rounds. A circuit does — it IS rounds of the whole block — so its members
 * cannot disagree about how many there are. A superset (and everything else)
 * is free to pair 5 sets of one thing with 3 of another, which is why only a
 * circuit is held to agreement.
 */
export function agreesOnSets(kind?: string): boolean {
  return kind === 'circuit'
}

/**
 * Make every member of a circuit agree with its first member's set count.
 *
 * Reported from the field: a 3-set exercise added to a 5-set one and turned
 * into a circuit rendered as five rounds with the second exercise missing from
 * two of them — a shape nobody can run. The first member is the one the
 * circuit was built on, so it wins, and `groupRounds` follows so the flow
 * builder and the group header quote the same number.
 *
 * Only circuits are touched. Supersets are left exactly as they are.
 */
export function alignCircuitSets<T extends GroupableExercise>(list: T[]): T[] {
  const next = [...list]
  let changed = false
  let i = 0
  while (i < next.length) {
    const head = next[i]!
    if (!head.groupId || !agreesOnSets(head.groupType)) {
      i++
      continue
    }
    let last = i
    while (last + 1 < next.length && next[last + 1]!.groupId === head.groupId) last++
    if (last > i) {
      const rounds = Math.max(1, Math.floor(head.sets ?? DEFAULT_SETS))
      for (let k = i; k <= last; k++) {
        const ex = next[k]!
        if (ex.sets === rounds && ex.groupRounds === rounds) continue
        next[k] = { ...ex, sets: rounds, groupRounds: rounds }
        changed = true
      }
    }
    i = last + 1
  }
  return changed ? next : list
}

/**
 * Change one exercise's set count, keeping a circuit in agreement.
 *
 * Inside a circuit the count is a property of the BLOCK, not of the exercise
 * standing in it, so editing any member edits all of them — the member asked
 * for a different number of rounds, not for a circuit that cannot be run.
 * Outside a circuit only the one exercise moves, exactly as before.
 */
export function setSetsAt<T extends GroupableExercise>(list: T[], index: number, sets: number): T[] {
  const target = list[index]
  if (!target) return list
  const value = Math.max(1, Math.floor(sets) || 1)
  const circuit = !!target.groupId && agreesOnSets(target.groupType)
  return list.map((ex, i) => {
    if (i !== index && !(circuit && ex.groupId === target.groupId)) return ex
    return circuit ? { ...ex, sets: value, groupRounds: value } : { ...ex, sets: value }
  })
}

/** Below this many exercises, a session reads as thin — the add-exercise button calls attention to itself. */
export const RECOMMENDED_MIN_EXERCISES = 4

/** Whether the workout is thin enough that "Add exercise" should call attention to itself. */
export function needsMoreExercises(exerciseCount: number): boolean {
  return exerciseCount < RECOMMENDED_MIN_EXERCISES
}

/**
 * Whether to ask "finish with two exercises?" on the way out.
 *
 * Only for a session the member assembled themselves — a three-exercise day in
 * a program is the coach's call and gets no second-guessing — and only once:
 * answering "finish anyway" settles it for the rest of the session.
 */
export function shouldWarnBeforeFinish(opts: {
  selfBuilt: boolean
  exerciseCount: number
  alreadyAsked: boolean
}): boolean {
  if (!opts.selfBuilt || opts.alreadyAsked) return false
  return needsMoreExercises(opts.exerciseCount)
}

/** What a group of this kind and size is called on screen. */
export function groupLabelFor(kind: GroupKind, size: number): string {
  if (kind === 'circuit') return 'Circuit'
  if (kind === 'triset') return 'Triset'
  if (kind === 'giant_set') return 'Giant set'
  return size > 2 ? 'Superset' : 'Superset'
}

/**
 * The kind a group of this size naturally reads as, when the member just says
 * "group these": two is a superset, three a triset, four or more a giant set.
 * Circuits stay an explicit choice — a circuit is an intent, not a headcount.
 */
export function naturalKindFor(size: number): GroupKind {
  if (size >= 4) return 'giant_set'
  if (size === 3) return 'triset'
  return 'superset'
}

/** A group id that cannot collide with one already in the list. */
export function newGroupId(list: Pick<WorkoutExercise, 'groupId'>[], seed?: number): string {
  const taken = new Set(list.map(e => e.groupId).filter(Boolean) as string[])
  let n = Math.max(1, Math.floor(seed ?? 1))
  let id = `adhoc-${n}`
  while (taken.has(id)) id = `adhoc-${++n}`
  return id
}

function identityOrder(n: number): number[] {
  return Array.from({ length: n }, (_, i) => i)
}

/** Append an exercise to the end of the workout. */
export function appendExercise<T extends GroupableExercise>(list: T[], ex: T): MutationResult<T> & { index: number } {
  return { exercises: [...list, ex], order: [...identityOrder(list.length), -1], index: list.length }
}

/**
 * Insert an exercise directly after `afterIndex`. Used for "add it into the
 * superset I am standing in" — the new exercise has to sit beside its group or
 * the flow builder will not interleave it.
 */
export function insertExerciseAfter<T extends GroupableExercise>(list: T[], afterIndex: number, ex: T): MutationResult<T> & { index: number } {
  const at = Math.max(-1, Math.min(afterIndex, list.length - 1)) + 1
  const exercises = [...list.slice(0, at), ex, ...list.slice(at)]
  const order = [...identityOrder(list.length).slice(0, at), -1, ...identityOrder(list.length).slice(at)]
  return { exercises, order, index: at }
}

/**
 * Add an exercise into the group the given exercise belongs to (or start a new
 * group of the two, when it has none). This is the one-tap "superset this with
 * what I am doing" path.
 */
export function addIntoGroup<T extends GroupableExercise>(
  list: T[],
  anchorIndex: number,
  ex: T,
  kind: GroupKind = 'superset',
): MutationResult<T> & { index: number; groupId: string } {
  const anchor = list[anchorIndex]
  if (!anchor) {
    const appended = appendExercise(list, ex)
    return { ...appended, groupId: '' }
  }
  if (anchor.groupId) {
    // Slide in behind the last member of the existing group.
    let last = anchorIndex
    while (last + 1 < list.length && list[last + 1]?.groupId === anchor.groupId) last++
    const inserted = insertExerciseAfter(list, last, {
      ...ex,
      groupId: anchor.groupId,
      groupType: anchor.groupType,
      groupLabel: anchor.groupLabel,
      groupRest: anchor.groupRest,
      groupRounds: anchor.groupRounds,
    })
    const size = inserted.exercises.filter(e => e.groupId === anchor.groupId).length
    const relabelled = inserted.exercises.map(e =>
      e.groupId === anchor.groupId
        ? { ...e, groupLabel: groupLabelFor((e.groupType as GroupKind) || 'superset', size) }
        : e,
    )
    // Joining a circuit means running its rounds — whatever count the sheet
    // offered, the block it is joining decides.
    return { ...inserted, exercises: alignCircuitSets(relabelled), groupId: anchor.groupId }
  }
  // No group yet: put the new exercise right after the anchor and marry the two.
  const inserted = insertExerciseAfter(list, anchorIndex, ex)
  const grouped = groupIndexes(inserted.exercises, [anchorIndex, inserted.index], kind)
  return {
    exercises: grouped.exercises,
    // Compose the two permutations so the caller moves its set data once.
    order: grouped.order.map(i => (i === -1 ? -1 : inserted.order[i] ?? -1)),
    // The pair is already adjacent, so grouping does not move the new exercise.
    index: inserted.index,
    groupId: grouped.groupId,
  }
}

/**
 * Make the given exercises one group, moving them together at the position of
 * the first one. Returns the permutation so set data can follow its exercise.
 */
export function groupIndexes<T extends GroupableExercise>(
  list: T[],
  indexes: number[],
  kind: GroupKind = 'superset',
  opts?: { rounds?: number; rest?: string; groupId?: string },
): MutationResult<T> & { groupId: string; indexes: number[] } {
  const picked = [...new Set(indexes)].filter(i => i >= 0 && i < list.length).sort((a, b) => a - b)
  if (picked.length < 2) return { exercises: list, order: identityOrder(list.length), groupId: '', indexes: picked }

  const groupId = opts?.groupId ?? newGroupId(list, picked[0]! + 1)
  const label = groupLabelFor(kind, picked.length)
  const anchor = picked[0]!

  const order: number[] = []
  for (let i = 0; i < anchor; i++) if (!picked.includes(i)) order.push(i)
  order.push(...picked)
  for (let i = anchor + 1; i < list.length; i++) if (!picked.includes(i)) order.push(i)

  // A circuit runs the whole block for the same number of rounds, so its
  // members are brought into agreement the moment it is made: an explicit
  // round count wins, otherwise the first exercise picked sets it.
  const circuitSets = agreesOnSets(kind)
    ? Math.max(1, Math.floor(opts?.rounds ?? list[anchor]?.sets ?? DEFAULT_SETS))
    : 0

  const exercises = order.map(oldIdx => {
    const ex = list[oldIdx]!
    if (!picked.includes(oldIdx)) return ex
    return {
      ...ex,
      groupId,
      groupType: kind,
      groupLabel: label,
      ...(circuitSets ? { sets: circuitSets, groupRounds: circuitSets } : {}),
      ...(opts?.rounds ? { groupRounds: opts.rounds } : {}),
      ...(opts?.rest ? { groupRest: opts.rest } : {}),
    }
  })

  const start = order.indexOf(picked[0]!)
  return { exercises, order, groupId, indexes: picked.map((_, i) => start + i) }
}

/** The bounds of the group the exercise at `index` belongs to, or null. */
function groupBoundsAt(list: Pick<WorkoutExercise, 'groupId'>[], index: number): { first: number; last: number; groupId: string } | null {
  const gid = list[index]?.groupId
  if (!gid) return null
  let first = index
  let last = index
  while (first - 1 >= 0 && list[first - 1]?.groupId === gid) first--
  while (last + 1 < list.length && list[last + 1]?.groupId === gid) last++
  return { first, last, groupId: gid }
}

/**
 * Re-badge the group the exercise at `index` belongs to as another kind —
 * "this is a circuit, not a superset".
 *
 * The builder used to be able to make supersets and nothing else, so a circuit
 * could only be assembled mid-session from the live view. Switching TO a
 * circuit brings the block's set counts into agreement; switching away leaves
 * them where they are, because they are the member's numbers now.
 */
export function setGroupKindAt<T extends GroupableExercise>(list: T[], index: number, kind: GroupKind): MutationResult<T> {
  const bounds = groupBoundsAt(list, index)
  if (!bounds) return { exercises: list, order: identityOrder(list.length) }
  const size = bounds.last - bounds.first + 1
  const label = groupLabelFor(kind, size)
  const relabelled = list.map((ex, i) =>
    i >= bounds.first && i <= bounds.last ? { ...ex, groupType: kind, groupLabel: label } : ex,
  )
  return { exercises: alignCircuitSets(relabelled), order: identityOrder(list.length) }
}

/**
 * Pull the exercise that follows a group into it — the gesture that turns a
 * pair into a real circuit of three, four, five.
 *
 * Order is unchanged: the newcomer already sits directly behind the group's
 * last member, which is the one place grouping needs it to be.
 */
export function addNextIntoGroup<T extends GroupableExercise>(list: T[], index: number): MutationResult<T> & { groupId: string } {
  const bounds = groupBoundsAt(list, index)
  if (!bounds) return { exercises: list, order: identityOrder(list.length), groupId: '' }
  const next = bounds.last + 1
  if (next >= list.length) return { exercises: list, order: identityOrder(list.length), groupId: bounds.groupId }
  const head = list[bounds.first]!
  const kind = (head.groupType as GroupKind) || 'superset'
  const indexes: number[] = []
  for (let i = bounds.first; i <= next; i++) indexes.push(i)
  const grouped = groupIndexes(list, indexes, kind, {
    groupId: bounds.groupId,
    ...(head.groupRounds ? { rounds: head.groupRounds } : {}),
    ...(head.groupRest ? { rest: head.groupRest } : {}),
  })
  return { exercises: grouped.exercises, order: grouped.order, groupId: bounds.groupId }
}

/** Break up the group the exercise at `index` belongs to. Order is unchanged. */
export function ungroupAt<T extends GroupableExercise>(list: T[], index: number): MutationResult<T> {
  const gid = list[index]?.groupId
  if (!gid) return { exercises: list, order: identityOrder(list.length) }
  const exercises = list.map(ex => {
    if (ex.groupId !== gid) return ex
    const next = { ...ex }
    delete next.groupId
    delete next.groupType
    delete next.groupLabel
    delete next.groupRest
    delete next.groupRounds
    return next
  })
  return { exercises, order: identityOrder(list.length) }
}

/** Remove an exercise, dissolving a group that would be left with one member. */
export function removeExercise<T extends GroupableExercise>(list: T[], index: number): MutationResult<T> {
  if (index < 0 || index >= list.length) return { exercises: list, order: identityOrder(list.length) }
  const gid = list[index]?.groupId
  const order = identityOrder(list.length).filter(i => i !== index)
  let exercises = order.map(i => list[i]!)
  if (gid && exercises.filter(e => e.groupId === gid).length < 2) {
    exercises = exercises.map(e => {
      if (e.groupId !== gid) return e
      const next = { ...e }
      delete next.groupId
      delete next.groupType
      delete next.groupLabel
      delete next.groupRest
      delete next.groupRounds
      return next
    })
  }
  return { exercises, order }
}

/**
 * Move an exercise up or down the workout.
 *
 * Reordering can carry an exercise out of the superset it belonged to, or drop
 * an outsider into the middle of one — `sanitizeGroups` settles that afterwards,
 * because a group whose members are no longer neighbours is not a group.
 */
export function moveExercise<T extends GroupableExercise>(list: T[], from: number, to: number): MutationResult<T> {
  if (from === to || from < 0 || from >= list.length || to < 0 || to >= list.length) {
    return { exercises: list, order: identityOrder(list.length) }
  }
  const order = identityOrder(list.length)
  const [moved] = order.splice(from, 1)
  order.splice(to, 0, moved!)
  return { exercises: sanitizeGroups(order.map(i => list[i]!)), order }
}

/** A workout with nothing in it is not a workout — the last exercise stays. */
export function canRemoveExercise(list: unknown[]): boolean {
  return list.length > 1
}

/**
 * Move a caller's parallel array (set data, per-exercise progress, …) through a
 * mutation. `make(newIndex)` supplies a fresh row for an exercise that did not
 * exist before.
 */
export function applyOrder<R>(rows: R[], order: number[], make: (newIndex: number) => R): R[] {
  return order.map((oldIdx, newIdx) => (oldIdx === -1 ? make(newIdx) : rows[oldIdx] ?? make(newIdx)))
}

/** The same, for a keyed record such as `swappedExercises` (index → value). */
export function applyOrderToRecord<V>(record: Record<number, V>, order: number[]): Record<number, V> {
  const next: Record<number, V> = {}
  order.forEach((oldIdx, newIdx) => {
    if (oldIdx !== -1 && record[oldIdx] !== undefined) next[newIdx] = record[oldIdx] as V
  })
  return next
}

/**
 * Where a step index lands after a mutation. The live view is sitting on a
 * step when the workout changes; without this the member gets teleported.
 */
export function remapIndex(order: number[], oldIndex: number): number {
  const at = order.indexOf(oldIndex)
  return at === -1 ? Math.min(oldIndex, Math.max(0, order.length - 1)) : at
}

// ── Restoring an added exercise from a saved log ─────────────────────────────

/** One exercise as it comes back from a saved workout log. */
export interface SavedLogExercise {
  name: string
  exerciseSlug?: string
  sets?: Array<{ reps?: number | null; weight?: number | null; duration?: number | null; completed?: boolean }>
  groupId?: string
  groupType?: string
  groupLabel?: string
  groupRounds?: number
  addedAdHoc?: boolean
  prescription?: { sets?: number; reps?: string; duration?: string; rest?: string; trackingType?: string }
}

/**
 * Rebuild the exercise a member added mid-session from what the log kept.
 * The prescription is authoritative when present; otherwise the shape of the
 * logged sets tells us enough (a duration with no reps is timed work).
 */
export function exerciseFromLog(saved: SavedLogExercise): AdHocExercise {
  const p = saved.prescription
  const first = saved.sets?.[0]
  const timed = !!first && first.duration != null && !(first.reps && first.reps > 0)
  return {
    name: saved.name,
    ...(saved.exerciseSlug ? { exerciseSlug: saved.exerciseSlug } : {}),
    trackingType: p?.trackingType || (timed ? 'time' : 'reps_weight'),
    sets: p?.sets ?? Math.max(1, saved.sets?.length ?? 1),
    reps: p?.reps ?? (!timed && first?.reps ? String(first.reps) : ''),
    ...(p?.duration ? { duration: p.duration } : timed && first?.duration ? { duration: `${first.duration}` } : {}),
    ...(p?.rest ? { rest: p.rest } : {}),
    ...(saved.groupId ? { groupId: saved.groupId } : {}),
    ...(saved.groupType ? { groupType: saved.groupType } : {}),
    ...(saved.groupLabel ? { groupLabel: saved.groupLabel } : {}),
    ...(saved.groupRounds ? { groupRounds: saved.groupRounds } : {}),
    addedAdHoc: true,
  }
}

/**
 * Merge exercises added mid-session back into a programmed workout on resume.
 *
 * A program workout's exercise list is rebuilt from the program every time it
 * loads, so anything added during the session would vanish on reload and its
 * logged sets would be orphaned. Anything the log carries past the program's
 * own list — or explicitly flagged as added — comes back, in order, keeping
 * whatever group it was put in.
 */
export function mergeAdHocFromLog<T extends GroupableExercise>(
  planned: T[],
  saved: SavedLogExercise[] | undefined,
): (T | AdHocExercise)[] {
  if (!saved?.length) return planned
  const extra = saved
    .map((s, i) => ({ s, i }))
    .filter(({ s, i }) => s.addedAdHoc === true || i >= planned.length)
    .map(({ s }) => exerciseFromLog(s))
  if (!extra.length) return planned
  return [...planned, ...extra]
}

/**
 * Drop group fields from any group that no longer holds together: fewer than
 * two members, or members that are no longer neighbours. Reordering is free to
 * split a superset, and a split superset that still claims to be one is worse
 * than none — the flow builder would stop interleaving it while the card kept
 * saying "Superset".
 */
export function sanitizeGroups<T extends GroupableExercise>(list: T[]): T[] {
  const runs = new Map<string, number[]>()
  list.forEach((ex, i) => {
    if (!ex.groupId) return
    const at = runs.get(ex.groupId)
    if (at) at.push(i)
    else runs.set(ex.groupId, [i])
  })
  const broken = new Set<string>()
  for (const [gid, idxs] of runs) {
    const contiguous = idxs.every((v, k) => k === 0 || v === idxs[k - 1]! + 1)
    if (idxs.length < 2 || !contiguous) broken.add(gid)
  }
  if (!broken.size) return list
  return list.map(ex => {
    if (!ex.groupId || !broken.has(ex.groupId)) return ex
    const next = { ...ex }
    delete next.groupId
    delete next.groupType
    delete next.groupLabel
    delete next.groupRest
    delete next.groupRounds
    return next
  })
}

/** The prescription to persist beside an added exercise's logged sets. */
export function prescriptionOf(ex: WorkoutExercise): SavedLogExercise['prescription'] {
  return {
    sets: Math.max(1, ex.sets ?? 1),
    ...(ex.reps ? { reps: ex.reps } : {}),
    ...(ex.duration ? { duration: ex.duration } : {}),
    ...(ex.rest ? { rest: ex.rest } : {}),
    ...(ex.trackingType ? { trackingType: ex.trackingType } : {}),
  }
}
