// ── A COPY. DO NOT EDIT THIS FILE. ─────────────────────────────────────────
//
// Source: webapp/lib/workout/position.ts
//
// NP-058 applying NP-017: the training, streak and dashboard logic is pure,
// so both apps run the SAME code instead of two implementations of it. A
// behaviour change lands on the WEB first and is re-copied here, and
// webapp/tests/unit/nativeParity/trainingModules.test.ts runs this copy
// against the web source over a fixture table and fails until it is.
// Re-copy procedure: expo/README.md, "Re-copying a training module".
//
// The only edits a copy may carry:
//  * imports rewritten to relative paths, and the webapp model/store types
//    they were type-only imports of mirrored in ../types.ts;
//  * the non-null assertions `noUncheckedIndexedAccess` asks for (set by
//    expo/tsconfig.json, which typechecks these sources; webapp does not
//    set it). Assertions only — no runtime branch is added or removed.
//
// And for this file:
//  * Carries `resolveStartStep`, the scope keys and the age rule ONLY. The
//    web's read/write/clear wrappers are `localStorage`, which React Native
//    does not have; the native position store arrives with NP-081.
// ──────────────────────────────────────────────────────────────────────────
// Where you are in a workout — shared between the Live view and the Track view.
//
// The two views are one workout seen two ways, and flipping between them used
// to throw away your place: Live rebuilt its flow from scratch and started at
// set 1, so a member three sets into an exercise came back to the top and
// re-logged over work they had already done.
//
// Progress (the reps and weights) was already shared. This is the other half:
// the exercise and set you were standing on.
//
// The storage wrapper is deliberately thin and total — a missing, stale or
// corrupt entry just means "no opinion", and the caller falls back to the first
// incomplete set, which is what it did before.

export interface WorkoutPosition {
  exerciseIndex: number
  setIndex: number
  /** Epoch ms, so a position from a workout two days ago is ignored. */
  at: number
}

/** Positions older than this are treated as no position at all. */
export const POSITION_MAX_AGE_MS = 12 * 60 * 60 * 1000

/**
 * The storage KEY for a scope. The web's `localStorage` wrapper and whatever
 * the native store ends up being (AsyncStorage — NP-081) must agree on it, so
 * it travels with the pure half rather than living inside either wrapper.
 */
export function positionKey(scope: string): string {
  return `workout_pos_${scope}`
}

/** The storage scope for a quick session. */
export function quickScope(sessionId: string): string {
  return `quick:${sessionId}`
}

/** The storage scope for a program workout day. */
export function programScope(programId: string, day: string): string {
  return `program:${programId}:${day}`
}

/**
 * Is this what a stored position claims to be, and is it still current?
 *
 * The web's `readPosition` is `localStorage.getItem` + `JSON.parse` + these
 * checks; the parsing is the part that has rules, so it is the part that
 * travels. `null` means "no opinion" and the caller falls back to the first
 * incomplete set, exactly as before.
 */
export function parsePosition(raw: unknown, now = Date.now()): WorkoutPosition | null {
  const p = raw as Partial<WorkoutPosition> | null | undefined
  if (typeof p?.exerciseIndex !== 'number' || typeof p?.setIndex !== 'number') return null
  if (typeof p.at !== 'number' || now - p.at > POSITION_MAX_AGE_MS) return null
  return { exerciseIndex: p.exerciseIndex, setIndex: p.setIndex, at: p.at }
}

/** Is this position worth writing at all? (The web guards the same two.) */
export function isWritablePosition(scope: string, exerciseIndex: number, setIndex: number): boolean {
  if (!scope) return false
  return Number.isFinite(exerciseIndex) && Number.isFinite(setIndex)
}

interface StepLike { exerciseIndex: number; setIndex: number }
interface SetLike { completed?: boolean }

/**
 * Which step to open on.
 *
 * The remembered position wins — that is the whole point of remembering it, and
 * it is what makes flipping Track↔Live feel like one workout. It is only
 * overruled when the step no longer exists (the workout changed underneath it),
 * in which case we fall back to the first set that still needs doing, and then
 * to the last step of the workout.
 */
export function resolveStartStep(
  flow: StepLike[],
  data: SetLike[][],
  saved?: WorkoutPosition | null,
): number {
  if (flow.length === 0) return 0
  if (saved) {
    const at = flow.findIndex(s => s.exerciseIndex === saved.exerciseIndex && s.setIndex === saved.setIndex)
    if (at !== -1) return at
  }
  for (let i = 0; i < flow.length; i++) {
    const step = flow[i]!
    if (!data[step.exerciseIndex]?.[step.setIndex]?.completed) return i
  }
  return flow.length - 1
}
