// ── A COPY. DO NOT EDIT THIS FILE. ─────────────────────────────────────────
//
// Source: webapp/lib/quickSession/log.ts
//
// NP-058 applying NP-017: the training, streak and dashboard logic is pure,
// so both apps run the SAME code instead of two implementations of it. A
// behaviour change lands on the WEB first and is re-copied here, and
// webapp/tests/unit/nativeParity/trainingModules.test.ts runs this copy
// against the web source over a fixture table and fails until it is.
// Re-copy procedure: expo/README.md, "Re-copying a training module".
//
// The only edits a copy may carry:
//  * imports rewritten to relative paths, and the webapp model/store types
//    they were type-only imports of mirrored in ../types.ts;
//  * the non-null assertions `noUncheckedIndexedAccess` asks for (set by
//    expo/tsconfig.json, which typechecks these sources; webapp does not
//    set it). Assertions only — no runtime branch is added or removed.
//
// And for this file:
//  * `logQuickSession` is NOT copied: it reads the bearer token out of
//    `localStorage` and POSTs to a same-origin relative URL. Native saves
//    workouts through `@become/api-client`. The pure half is here.
// ──────────────────────────────────────────────────────────────────────────
// Shared "log or plan a quick session without playing it" helper — used by the
// generated-session overview AND the manual SessionBuilder, so both surfaces can
// backfill a past workout (performedAt in the past → logged done) or plan a
// future one (future date → saved as planned, startable later). Client-side.

import type { DraftExercise } from '../types'

export function localDateStr(d = new Date()): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
}

const firstInt = (s?: string): number | undefined => {
  const m = s ? String(s).match(/\d+/) : null
  return m ? parseInt(m[0], 10) : undefined
}

// Turn the planned exercises into log entries: every planned set carries its
// prescribed reps (or duration). `done` marks the sets completed — true when
// logging a past/today session, false when planning a future one.
export function buildLoggedExercises(exercises: DraftExercise[], done: boolean) {
  return exercises.map((ex) => {
    const nSets = Math.max(1, Number(ex.sets) || 1)
    const reps = firstInt(ex.reps)
    const durSec = firstInt(ex.duration)
    return {
      name: ex.name,
      ...(ex.exerciseSlug && { exerciseSlug: ex.exerciseSlug }),
      sets: Array.from({ length: nSets }, (_, i) => ({
        setNumber: i + 1,
        ...(reps != null && { reps }),
        ...(durSec != null && { duration: durSec }),
        completed: done,
      })),
      // A superset planned here is still a superset when the session is
      // started later — the log is what the planned session is rebuilt from.
      ...(ex.groupId && { groupId: ex.groupId }),
      ...(ex.groupType && { groupType: ex.groupType }),
      ...(ex.groupLabel && { groupLabel: ex.groupLabel }),
      ...(ex.groupRounds && { groupRounds: ex.groupRounds }),
      ...(ex.addedAdHoc && { addedAdHoc: true }),
      prescription: {
        sets: nSets,
        ...(ex.reps ? { reps: ex.reps } : {}),
        ...(ex.duration ? { duration: ex.duration } : {}),
        ...(ex.rest ? { rest: ex.rest } : {}),
        ...(ex.trackingType ? { trackingType: ex.trackingType } : {}),
      },
    }
  })
}

// `QuickLogInput` / `logQuickSession` stop here — see the note at the top of
// this file. Everything above is the pure half both apps share.
