import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  cardSize,
  layoutWeeks,
  overviewCamera,
  boundsOf,
  scrubTarget,
  neighbourFor,
  monthTicks,
  OVERVIEW_MAX_SCALE,
  OVERVIEW_MIN_SCALE,
} from '../src/becoming/layout';
import * as root from '../src/index';

// The copy of webapp/lib/becoming/layout.ts (NP-204). The lockstep against the
// web source is webapp/tests/unit/nativeParity/becomingLayout.test.ts, in the
// job that always runs; this suite holds the package itself to the shape the
// native stage relies on, and to its "do not edit" header.
describe('becoming/layout (the copy the native stage runs)', () => {
  const size = cardSize(390, 844);
  const wk = (index: number, altitude: number, step: 'up' | 'flat' | 'down' | 'start' = 'flat') => ({ index, altitude, step, score: 50, daysElapsed: 7 });
  const weeks = [wk(0, 0, 'start'), wk(1, 1, 'up'), wk(2, 1.25, 'flat'), wk(3, 0.9, 'down')];
  const pos = layoutWeeks(weeks, size);

  it('lays weeks out one column per week, altitude up, with the Horizon one past the last', () => {
    assert.equal(size.w, 350);
    assert.deepEqual(pos[1], { index: 1, x: size.col, y: -size.row });
    assert.equal(pos.length, 5);
    assert.equal(pos[4]!.horizon, true);
    assert.equal(pos[4]!.x, 4 * size.col);
  });

  it('frames the overview below the focus threshold', () => {
    const cam = overviewCamera(boundsOf(pos, size), pos, 390 - 32, 844 - 240);
    assert.ok(cam.s >= OVERVIEW_MIN_SCALE && cam.s < OVERVIEW_MAX_SCALE);
  });

  it('projects a drag onto the segment the finger moves along', () => {
    assert.equal(scrubTarget(pos, 1, -120, 0, 1)!.target, 2);
    assert.equal(scrubTarget(pos, 1, 140, 0, 1)!.target, 0);
    assert.equal(neighbourFor(pos, 1, 'up'), 2);
    assert.equal(neighbourFor(pos, 4, 'left'), null);
  });

  it('ticks the first week of each month, the year on January and the first', () => {
    const ticks = monthTicks([
      { index: 0, weekKey: '2025-12-28' },
      { index: 1, weekKey: '2026-01-04' },
      { index: 2, weekKey: '2026-02-01' },
    ]);
    assert.deepEqual(ticks, [
      { index: 0, label: 'Dec 2025' },
      { index: 1, label: 'Jan 2026' },
      { index: 2, label: 'Feb' },
    ]);
  });

  it('is exported from the package root, so the native stage imports it as @become/core', () => {
    assert.equal(root.layoutWeeks, layoutWeeks);
    assert.equal(root.OVERVIEW_MAX_SCALE, OVERVIEW_MAX_SCALE);
  });

  it('carries its "do not edit" header and names its web source', () => {
    // `@become/core` is an ES module, so there is no `__dirname` here.
    const here = path.dirname(fileURLToPath(import.meta.url));
    const head = fs.readFileSync(path.join(here, '../src/becoming/layout.ts'), 'utf8').slice(0, 2000);
    assert.match(head, /A COPY\. DO NOT EDIT THIS FILE\./);
    assert.match(head, /^\/\/ Source: webapp\/lib\/becoming\/layout\.ts$/m);
  });
});
