// Constants for the Exercise admin form. Values mirror the enum lists in
// `webapp/models/Exercise.ts` so the form fully covers the model.

export const CATEGORIES = [
  'strength',
  'power',
  'cardio',
  'plyometric',
  'calisthenics',
  'olympic',
  'strongman',
  'flexibility',
  'mobility',
  'warmup',
  'cooldown',
  'conditioning',
  'protocol',
] as const

export const MECHANICS = ['compound', 'isolation', 'n/a'] as const

export const ROLES = ['compound', 'secondary', 'accessory'] as const

export const MOVEMENT_PATTERNS = [
  'squat',
  'hinge',
  'lunge',
  'horizontal_push',
  'horizontal_pull',
  'vertical_push',
  'vertical_pull',
  'carry',
  'rotation',
  'anti_rotation',
  'anti_extension',
  'anti_lateral_flexion',
  'knee_extension',
  'knee_flexion',
  'hip_extension',
  'horizontal_adduction',
  'shoulder_abduction',
  'shoulder_flexion',
  'elbow_flexion',
  'elbow_extension',
  'ankle_flexion',
  'scapular_retraction',
  'triple_extension',
  'gait',
  'n/a',
] as const

export const LATERALITY = ['bilateral', 'unilateral', 'alternating', 'n/a'] as const

export const DIFFICULTY = ['beginner', 'intermediate', 'advanced', 'expert'] as const

export const TRACKING_TYPES = [
  'reps_weight',
  'reps_bodyweight',
  'time',
  'time_distance',
  'intervals',
  'reps_only',
  'none',
] as const

export const BODY_REGIONS = ['upper_body', 'lower_body', 'core', 'full_body'] as const

export const MUSCLES = [
  'chest',
  'upper_chest',
  'lower_chest',
  'lats',
  'upper_back',
  'mid_back',
  'lower_back',
  'rhomboids',
  'traps',
  'teres_major',
  'front_delts',
  'side_delts',
  'rear_delts',
  'rotator_cuff',
  'biceps',
  'triceps',
  'forearms',
  'brachialis',
  'grip',
  'abs',
  'obliques',
  'transverse_abdominis',
  'hip_flexors',
  'erector_spinae',
  'quads',
  'hamstrings',
  'glutes',
  'calves',
  'adductors',
  'abductors',
  'full_body',
] as const

export const EQUIPMENT = [
  'barbell',
  'dumbbell',
  'kettlebell',
  'ez_bar',
  'trap_bar',
  'safety_squat_bar',
  'cable',
  'leg_press',
  'leg_extension',
  'leg_curl',
  'hack_squat',
  'chest_press_machine',
  'shoulder_press_machine',
  'lat_pulldown',
  'seated_row_machine',
  'low_row_machine',
  'pec_deck',
  'hip_abduction_machine',
  'hip_adduction_machine',
  'calf_raise_machine',
  'preacher_curl_machine',
  'belt_squat_machine',
  'lateral_raise_machine',
  'rear_delt_machine',
  'smith_machine',
  'glute_ham_raise',
  'back_extension',
  'sled',
  'flat_bench',
  'incline_bench',
  'decline_bench',
  'squat_rack',
  'pull_up_bar',
  'dip_station',
  'resistance_band',
  'foam_roller',
  'exercise_mat',
  'box',
  'chair',
  'ab_wheel',
  'medicine_ball',
  'treadmill',
  'stationary_bike',
  'rowing_machine',
  'assault_bike',
  'elliptical',
  'jump_rope',
  'backpack',
  'towel',
  'bodyweight',
  'none',
] as const
