// Keeps androidx.work-runtime-ktx in step with androidx.work-runtime on Android.
//
// react-native-android-widget asks for work-runtime 2.8.1. expo-widgets pulls in
// androidx.glance 1.2.0-rc01, which asks for work-runtime-ktx 2.7.1. Gradle
// lifts work-runtime to 2.8.1 but leaves work-runtime-ktx at 2.7.1. Since 2.8.0
// the ktx classes (CoroutineWorker, ListenableFutureKt, ...) ship inside
// work-runtime and work-runtime-ktx is an empty artifact, so 2.7.1 + 2.8.1 puts
// the same classes on the classpath twice and checkReleaseDuplicateClasses
// fails. A constraint lifting work-runtime-ktx to 2.8.1 removes the copy.
//
// It lives in a config plugin because android/ is generated by `expo prebuild`.
const { withAppBuildGradle } = require("expo/config-plugins");

const MARKER = "// become: androidx.work alignment";
const WORK_VERSION = "2.8.1";

const BLOCK = `
${MARKER}
dependencies {
    constraints {
        implementation("androidx.work:work-runtime-ktx:${WORK_VERSION}") {
            because("work-runtime-ktx < 2.8 duplicates classes now in work-runtime (glance asks for 2.7.1)")
        }
    }
}
`;

module.exports = function withAndroidxWorkAlignment(config) {
  return withAppBuildGradle(config, (mod) => {
    if (mod.modResults.language !== "groovy") {
      throw new Error("withAndroidxWorkAlignment expects a Groovy app/build.gradle");
    }
    if (!mod.modResults.contents.includes(MARKER)) {
      mod.modResults.contents += BLOCK;
    }
    return mod;
  });
};
