import mongoose from 'mongoose'
import path from 'path'
import * as dotenv from 'dotenv'
import FoodItem, { IFoodItem } from '../models/FoodItem'

// Load environment variables from .env.local
dotenv.config({ path: path.join(__dirname, '../.env.local') })

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://admin:admin123@localhost:27017/jondonfitdb?authSource=admin'

type FoodSeed = Omit<IFoodItem, '_id' | 'usageCount' | 'createdAt' | 'updatedAt'>

const foods: FoodSeed[] = [
  // ─────────────────────────────────────────────────────────
  //  PROTEINS (~40 items)
  // ─────────────────────────────────────────────────────────
  {
    name: 'Chicken Breast (raw)',
    category: 'Protein',
    servingSize: 112,
    servingUnit: 'g',
    alternateServings: [{ label: '1 breast (6 oz)', multiplier: 1.5 }],
    nutrition: { calories: 120, protein: 26, carbs: 0, fats: 1.5, fiber: 0, sugar: 0, sodium: 60, saturatedFat: 0.4 },
    isVerified: true,
  },
  {
    name: 'Chicken Breast (cooked)',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'g',
    alternateServings: [{ label: '1 breast (5 oz)', multiplier: 1.4 }],
    nutrition: { calories: 165, protein: 31, carbs: 0, fats: 3.6, fiber: 0, sugar: 0, sodium: 74, saturatedFat: 1 },
    isVerified: true,
  },
  {
    name: 'Chicken Breast (grilled)',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'g',
    alternateServings: [{ label: '1 breast (5 oz)', multiplier: 1.4 }],
    nutrition: { calories: 165, protein: 31, carbs: 0, fats: 3.6, fiber: 0, sugar: 0, sodium: 74, saturatedFat: 1 },
    isVerified: true,
  },
  {
    name: 'Chicken Thigh (boneless, cooked)',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'g',
    alternateServings: [{ label: '1 thigh', multiplier: 0.85 }],
    nutrition: { calories: 209, protein: 26, carbs: 0, fats: 10.9, fiber: 0, sugar: 0, sodium: 84, saturatedFat: 3 },
    isVerified: true,
  },
  {
    name: 'Turkey Breast (cooked)',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'g',
    alternateServings: [{ label: '3 slices', multiplier: 0.85 }],
    nutrition: { calories: 135, protein: 30, carbs: 0, fats: 0.7, fiber: 0, sugar: 0, sodium: 55, saturatedFat: 0.2 },
    isVerified: true,
  },
  {
    name: 'Ground Turkey (93% lean)',
    category: 'Protein',
    servingSize: 112,
    servingUnit: 'g',
    alternateServings: [{ label: '1/4 lb patty', multiplier: 1 }],
    nutrition: { calories: 170, protein: 21, carbs: 0, fats: 9, fiber: 0, sugar: 0, sodium: 80, saturatedFat: 2.5 },
    isVerified: true,
  },
  {
    name: 'Ground Beef (90/10)',
    category: 'Protein',
    servingSize: 112,
    servingUnit: 'g',
    alternateServings: [{ label: '1/4 lb patty', multiplier: 1 }],
    nutrition: { calories: 200, protein: 22, carbs: 0, fats: 11, fiber: 0, sugar: 0, sodium: 75, saturatedFat: 4.5 },
    isVerified: true,
  },
  {
    name: 'Ground Beef (80/20)',
    category: 'Protein',
    servingSize: 112,
    servingUnit: 'g',
    alternateServings: [{ label: '1/4 lb patty', multiplier: 1 }],
    nutrition: { calories: 280, protein: 19, carbs: 0, fats: 23, fiber: 0, sugar: 0, sodium: 75, saturatedFat: 9 },
    isVerified: true,
  },
  {
    name: 'Steak - Sirloin (cooked)',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'g',
    alternateServings: [{ label: '6 oz steak', multiplier: 1.7 }],
    nutrition: { calories: 206, protein: 26, carbs: 0, fats: 10.6, fiber: 0, sugar: 0, sodium: 56, saturatedFat: 4 },
    isVerified: true,
  },
  {
    name: 'Steak - Ribeye (cooked)',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'g',
    alternateServings: [{ label: '8 oz steak', multiplier: 2.27 }],
    nutrition: { calories: 271, protein: 27, carbs: 0, fats: 17, fiber: 0, sugar: 0, sodium: 58, saturatedFat: 7.4 },
    isVerified: true,
  },
  {
    name: 'Pork Chop (boneless, cooked)',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'g',
    alternateServings: [{ label: '1 chop (5 oz)', multiplier: 1.4 }],
    nutrition: { calories: 231, protein: 25, carbs: 0, fats: 14, fiber: 0, sugar: 0, sodium: 62, saturatedFat: 5 },
    isVerified: true,
  },
  {
    name: 'Pork Tenderloin (cooked)',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'g',
    alternateServings: [{ label: '4 oz serving', multiplier: 1.13 }],
    nutrition: { calories: 143, protein: 26, carbs: 0, fats: 3.5, fiber: 0, sugar: 0, sodium: 48, saturatedFat: 1.2 },
    isVerified: true,
  },
  {
    name: 'Bacon (cooked)',
    category: 'Protein',
    servingSize: 8,
    servingUnit: 'g',
    alternateServings: [{ label: '2 slices', multiplier: 2 }, { label: '3 slices', multiplier: 3 }],
    nutrition: { calories: 43, protein: 3, carbs: 0, fats: 3.3, fiber: 0, sugar: 0, sodium: 185, saturatedFat: 1.1 },
    isVerified: true,
  },
  {
    name: 'Salmon (Atlantic, cooked)',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'g',
    alternateServings: [{ label: '1 fillet (6 oz)', multiplier: 1.7 }],
    nutrition: { calories: 208, protein: 20, carbs: 0, fats: 13, fiber: 0, sugar: 0, sodium: 59, saturatedFat: 3.1 },
    isVerified: true,
  },
  {
    name: 'Tuna (canned in water, drained)',
    category: 'Protein',
    servingSize: 85,
    servingUnit: 'g',
    alternateServings: [{ label: '1 can (5 oz)', multiplier: 1.68 }],
    nutrition: { calories: 73, protein: 17, carbs: 0, fats: 0.8, fiber: 0, sugar: 0, sodium: 210, saturatedFat: 0.2 },
    isVerified: true,
  },
  {
    name: 'Shrimp (cooked)',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'g',
    alternateServings: [{ label: '10 large shrimp', multiplier: 0.7 }],
    nutrition: { calories: 99, protein: 24, carbs: 0.2, fats: 0.3, fiber: 0, sugar: 0, sodium: 111, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Tilapia (cooked)',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'g',
    alternateServings: [{ label: '1 fillet (4 oz)', multiplier: 1.13 }],
    nutrition: { calories: 128, protein: 26, carbs: 0, fats: 2.7, fiber: 0, sugar: 0, sodium: 56, saturatedFat: 0.9 },
    isVerified: true,
  },
  {
    name: 'Cod (cooked)',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'g',
    alternateServings: [{ label: '1 fillet (6 oz)', multiplier: 1.7 }],
    nutrition: { calories: 105, protein: 23, carbs: 0, fats: 0.9, fiber: 0, sugar: 0, sodium: 78, saturatedFat: 0.2 },
    isVerified: true,
  },
  {
    name: 'Egg (whole, large)',
    category: 'Protein',
    servingSize: 50,
    servingUnit: 'g',
    alternateServings: [{ label: '1 egg', multiplier: 1 }, { label: '2 eggs', multiplier: 2 }, { label: '3 eggs', multiplier: 3 }],
    nutrition: { calories: 72, protein: 6, carbs: 0.4, fats: 5, fiber: 0, sugar: 0.2, sodium: 71, saturatedFat: 1.6 },
    isVerified: true,
  },
  {
    name: 'Egg Whites (large)',
    category: 'Protein',
    servingSize: 33,
    servingUnit: 'g',
    alternateServings: [{ label: '1 white', multiplier: 1 }, { label: '3 whites', multiplier: 3 }, { label: '1/2 cup liquid', multiplier: 3.7 }],
    nutrition: { calories: 17, protein: 3.6, carbs: 0.2, fats: 0.1, fiber: 0, sugar: 0.2, sodium: 55, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Tofu (firm)',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'g',
    alternateServings: [{ label: '1/2 block', multiplier: 2 }],
    nutrition: { calories: 144, protein: 17, carbs: 3, fats: 8.7, fiber: 2.3, sugar: 0.6, sodium: 14, saturatedFat: 1.3 },
    isVerified: true,
  },
  {
    name: 'Tempeh',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'g',
    alternateServings: [{ label: '1/2 block', multiplier: 1.5 }],
    nutrition: { calories: 192, protein: 20, carbs: 8, fats: 11, fiber: 7, sugar: 0, sodium: 9, saturatedFat: 2.5 },
    isVerified: true,
  },
  {
    name: 'Whey Protein Powder',
    category: 'Protein',
    servingSize: 30,
    servingUnit: 'scoop',
    alternateServings: [{ label: '2 scoops', multiplier: 2 }],
    nutrition: { calories: 120, protein: 24, carbs: 3, fats: 1.5, fiber: 0, sugar: 1, sodium: 130, saturatedFat: 0.5 },
    isVerified: true,
  },
  {
    name: 'Casein Protein Powder',
    category: 'Protein',
    servingSize: 33,
    servingUnit: 'scoop',
    alternateServings: [{ label: '2 scoops', multiplier: 2 }],
    nutrition: { calories: 120, protein: 24, carbs: 4, fats: 1, fiber: 0, sugar: 1, sodium: 160, saturatedFat: 0.5 },
    isVerified: true,
  },
  {
    name: 'Deli Turkey Breast',
    category: 'Protein',
    servingSize: 56,
    servingUnit: 'g',
    alternateServings: [{ label: '4 slices', multiplier: 1 }, { label: '2 slices', multiplier: 0.5 }],
    nutrition: { calories: 60, protein: 11, carbs: 2, fats: 0.5, fiber: 0, sugar: 1, sodium: 450, saturatedFat: 0.2 },
    isVerified: true,
  },
  {
    name: 'Deli Ham',
    category: 'Protein',
    servingSize: 56,
    servingUnit: 'g',
    alternateServings: [{ label: '4 slices', multiplier: 1 }, { label: '2 slices', multiplier: 0.5 }],
    nutrition: { calories: 60, protein: 10, carbs: 2, fats: 1.5, fiber: 0, sugar: 1, sodium: 520, saturatedFat: 0.5 },
    isVerified: true,
  },
  {
    name: 'Chicken Sausage (link)',
    category: 'Protein',
    servingSize: 68,
    servingUnit: 'g',
    alternateServings: [{ label: '1 link', multiplier: 1 }],
    nutrition: { calories: 110, protein: 14, carbs: 2, fats: 5, fiber: 0, sugar: 1, sodium: 440, saturatedFat: 1.5 },
    isVerified: true,
  },
  {
    name: 'Italian Sausage (pork, cooked)',
    category: 'Protein',
    servingSize: 83,
    servingUnit: 'g',
    alternateServings: [{ label: '1 link', multiplier: 1 }],
    nutrition: { calories: 286, protein: 16, carbs: 1, fats: 23, fiber: 0, sugar: 0, sodium: 620, saturatedFat: 8.5 },
    isVerified: true,
  },
  {
    name: 'Lamb (ground, cooked)',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'g',
    alternateServings: [],
    nutrition: { calories: 283, protein: 24, carbs: 0, fats: 20, fiber: 0, sugar: 0, sodium: 77, saturatedFat: 8.3 },
    isVerified: true,
  },
  {
    name: 'Bison (ground, cooked)',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'g',
    alternateServings: [],
    nutrition: { calories: 146, protein: 24, carbs: 0, fats: 5, fiber: 0, sugar: 0, sodium: 68, saturatedFat: 2 },
    isVerified: true,
  },
  {
    name: 'Turkey Bacon (cooked)',
    category: 'Protein',
    servingSize: 16,
    servingUnit: 'g',
    alternateServings: [{ label: '2 slices', multiplier: 2 }],
    nutrition: { calories: 35, protein: 2, carbs: 0, fats: 3, fiber: 0, sugar: 0, sodium: 180, saturatedFat: 0.8 },
    isVerified: true,
  },
  {
    name: 'Rotisserie Chicken (breast meat)',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'g',
    alternateServings: [{ label: '1/4 chicken', multiplier: 1.5 }],
    nutrition: { calories: 170, protein: 28, carbs: 0, fats: 6, fiber: 0, sugar: 0, sodium: 350, saturatedFat: 1.7 },
    isVerified: true,
  },
  {
    name: 'Canned Chicken Breast',
    category: 'Protein',
    servingSize: 56,
    servingUnit: 'g',
    alternateServings: [{ label: '1 can (10 oz)', multiplier: 5 }],
    nutrition: { calories: 70, protein: 13, carbs: 0, fats: 1.5, fiber: 0, sugar: 0, sodium: 270, saturatedFat: 0.5 },
    isVerified: true,
  },
  {
    name: 'Canned Salmon',
    category: 'Protein',
    servingSize: 56,
    servingUnit: 'g',
    alternateServings: [{ label: '1 can (5 oz)', multiplier: 2.5 }],
    nutrition: { calories: 90, protein: 12, carbs: 0, fats: 5, fiber: 0, sugar: 0, sodium: 270, saturatedFat: 1.2 },
    isVerified: true,
  },
  {
    name: 'Sardines (canned in oil, drained)',
    category: 'Protein',
    servingSize: 55,
    servingUnit: 'g',
    alternateServings: [{ label: '1 can (3.75 oz)', multiplier: 1.93 }],
    nutrition: { calories: 130, protein: 13, carbs: 0, fats: 8, fiber: 0, sugar: 0, sodium: 290, saturatedFat: 2 },
    isVerified: true,
  },
  {
    name: 'Edamame (shelled)',
    category: 'Protein',
    servingSize: 80,
    servingUnit: 'g',
    alternateServings: [{ label: '1/2 cup', multiplier: 1 }],
    nutrition: { calories: 95, protein: 8.5, carbs: 7, fats: 4, fiber: 4, sugar: 2, sodium: 5, saturatedFat: 0.5 },
    isVerified: true,
  },
  {
    name: 'Black Beans (canned, drained)',
    category: 'Protein',
    servingSize: 130,
    servingUnit: 'g',
    alternateServings: [{ label: '1/2 cup', multiplier: 1 }],
    nutrition: { calories: 114, protein: 7.6, carbs: 20, fats: 0.5, fiber: 8.3, sugar: 0.3, sodium: 230, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Lentils (cooked)',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'g',
    alternateServings: [{ label: '1/2 cup', multiplier: 1 }],
    nutrition: { calories: 116, protein: 9, carbs: 20, fats: 0.4, fiber: 8, sugar: 1.8, sodium: 2, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Chickpeas (canned, drained)',
    category: 'Protein',
    servingSize: 130,
    servingUnit: 'g',
    alternateServings: [{ label: '1/2 cup', multiplier: 1 }],
    nutrition: { calories: 134, protein: 7, carbs: 22, fats: 2.2, fiber: 6, sugar: 4, sodium: 240, saturatedFat: 0.2 },
    isVerified: true,
  },

  // ─────────────────────────────────────────────────────────
  //  DAIRY (~20 items)
  // ─────────────────────────────────────────────────────────
  {
    name: 'Greek Yogurt (plain, nonfat)',
    category: 'Dairy',
    servingSize: 170,
    servingUnit: 'g',
    alternateServings: [{ label: '1 container (5.3 oz)', multiplier: 1 }],
    nutrition: { calories: 100, protein: 17, carbs: 6, fats: 0.7, fiber: 0, sugar: 6, sodium: 65, saturatedFat: 0.2 },
    isVerified: true,
  },
  {
    name: 'Greek Yogurt (plain, full fat)',
    category: 'Dairy',
    servingSize: 170,
    servingUnit: 'g',
    alternateServings: [{ label: '1 container (5.3 oz)', multiplier: 1 }],
    nutrition: { calories: 165, protein: 15, carbs: 7, fats: 9, fiber: 0, sugar: 7, sodium: 70, saturatedFat: 5 },
    isVerified: true,
  },
  {
    name: 'Regular Yogurt (low-fat, vanilla)',
    category: 'Dairy',
    servingSize: 170,
    servingUnit: 'g',
    alternateServings: [{ label: '1 container (6 oz)', multiplier: 1 }],
    nutrition: { calories: 154, protein: 6, carbs: 28, fats: 2, fiber: 0, sugar: 24, sodium: 85, saturatedFat: 1.2 },
    isVerified: true,
  },
  {
    name: 'Milk (whole)',
    category: 'Dairy',
    servingSize: 240,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 149, protein: 8, carbs: 12, fats: 8, fiber: 0, sugar: 12, sodium: 105, saturatedFat: 4.6 },
    isVerified: true,
  },
  {
    name: 'Milk (2%)',
    category: 'Dairy',
    servingSize: 240,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 122, protein: 8, carbs: 12, fats: 5, fiber: 0, sugar: 12, sodium: 100, saturatedFat: 3 },
    isVerified: true,
  },
  {
    name: 'Milk (skim / nonfat)',
    category: 'Dairy',
    servingSize: 240,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 83, protein: 8, carbs: 12, fats: 0.2, fiber: 0, sugar: 12, sodium: 103, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Almond Milk (unsweetened)',
    category: 'Dairy',
    servingSize: 240,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 30, protein: 1, carbs: 1, fats: 2.5, fiber: 0, sugar: 0, sodium: 170, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Oat Milk (original)',
    category: 'Dairy',
    servingSize: 240,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 120, protein: 3, carbs: 16, fats: 5, fiber: 2, sugar: 7, sodium: 100, saturatedFat: 0.5 },
    isVerified: true,
  },
  {
    name: 'Cheddar Cheese',
    category: 'Dairy',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '1 slice', multiplier: 0.75 }, { label: '1/4 cup shredded', multiplier: 1 }],
    nutrition: { calories: 113, protein: 7, carbs: 0.4, fats: 9.3, fiber: 0, sugar: 0.1, sodium: 185, saturatedFat: 5.3 },
    isVerified: true,
  },
  {
    name: 'Mozzarella Cheese (part skim)',
    category: 'Dairy',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '1 slice', multiplier: 0.75 }, { label: '1/4 cup shredded', multiplier: 1 }],
    nutrition: { calories: 86, protein: 7, carbs: 1, fats: 6, fiber: 0, sugar: 0.3, sodium: 175, saturatedFat: 3.7 },
    isVerified: true,
  },
  {
    name: 'Parmesan Cheese (grated)',
    category: 'Dairy',
    servingSize: 10,
    servingUnit: 'g',
    alternateServings: [{ label: '2 tbsp', multiplier: 1 }],
    nutrition: { calories: 42, protein: 3.6, carbs: 0.4, fats: 2.8, fiber: 0, sugar: 0.1, sodium: 165, saturatedFat: 1.8 },
    isVerified: true,
  },
  {
    name: 'Cottage Cheese (low-fat, 2%)',
    category: 'Dairy',
    servingSize: 113,
    servingUnit: 'g',
    alternateServings: [{ label: '1/2 cup', multiplier: 1 }],
    nutrition: { calories: 92, protein: 12, carbs: 5, fats: 2.6, fiber: 0, sugar: 4, sodium: 348, saturatedFat: 1.4 },
    isVerified: true,
  },
  {
    name: 'Cream Cheese',
    category: 'Dairy',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '2 tbsp', multiplier: 1 }],
    nutrition: { calories: 99, protein: 1.7, carbs: 1.6, fats: 9.8, fiber: 0, sugar: 0.7, sodium: 90, saturatedFat: 5.5 },
    isVerified: true,
  },
  {
    name: 'Butter',
    category: 'Fat',
    servingSize: 14,
    servingUnit: 'g',
    alternateServings: [{ label: '1 tbsp', multiplier: 1 }, { label: '1 pat', multiplier: 0.36 }],
    nutrition: { calories: 102, protein: 0.1, carbs: 0, fats: 11.5, fiber: 0, sugar: 0, sodium: 82, saturatedFat: 7.3 },
    isVerified: true,
  },
  {
    name: 'String Cheese (mozzarella)',
    category: 'Dairy',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '1 stick', multiplier: 1 }],
    nutrition: { calories: 80, protein: 7, carbs: 1, fats: 5, fiber: 0, sugar: 0, sodium: 200, saturatedFat: 3 },
    isVerified: true,
  },
  {
    name: 'Ricotta Cheese (part skim)',
    category: 'Dairy',
    servingSize: 62,
    servingUnit: 'g',
    alternateServings: [{ label: '1/4 cup', multiplier: 1 }],
    nutrition: { calories: 85, protein: 7, carbs: 3, fats: 5, fiber: 0, sugar: 1, sodium: 75, saturatedFat: 3 },
    isVerified: true,
  },
  {
    name: 'Sour Cream',
    category: 'Dairy',
    servingSize: 30,
    servingUnit: 'g',
    alternateServings: [{ label: '2 tbsp', multiplier: 1 }],
    nutrition: { calories: 57, protein: 0.7, carbs: 1.3, fats: 5.6, fiber: 0, sugar: 1, sodium: 15, saturatedFat: 3 },
    isVerified: true,
  },
  {
    name: 'Heavy Cream',
    category: 'Dairy',
    servingSize: 15,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 tbsp', multiplier: 1 }],
    nutrition: { calories: 51, protein: 0.4, carbs: 0.4, fats: 5.4, fiber: 0, sugar: 0.4, sodium: 6, saturatedFat: 3.4 },
    isVerified: true,
  },

  // ─────────────────────────────────────────────────────────
  //  GRAINS & CARBS (~25 items)
  // ─────────────────────────────────────────────────────────
  {
    name: 'White Rice (cooked)',
    category: 'Grain',
    servingSize: 158,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 206, protein: 4.3, carbs: 45, fats: 0.4, fiber: 0.6, sugar: 0, sodium: 1, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Brown Rice (cooked)',
    category: 'Grain',
    servingSize: 158,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 216, protein: 5, carbs: 45, fats: 1.8, fiber: 3.5, sugar: 0.7, sodium: 10, saturatedFat: 0.4 },
    isVerified: true,
  },
  {
    name: 'Quinoa (cooked)',
    category: 'Grain',
    servingSize: 185,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 222, protein: 8, carbs: 39, fats: 3.6, fiber: 5, sugar: 1.6, sodium: 13, saturatedFat: 0.4 },
    isVerified: true,
  },
  {
    name: 'Oats (rolled, dry)',
    category: 'Grain',
    servingSize: 40,
    servingUnit: 'g',
    alternateServings: [{ label: '1/2 cup', multiplier: 1 }, { label: '1 cup', multiplier: 2 }],
    nutrition: { calories: 150, protein: 5, carbs: 27, fats: 2.5, fiber: 4, sugar: 1, sodium: 0, saturatedFat: 0.4 },
    isVerified: true,
  },
  {
    name: 'Instant Oatmeal (plain, packet)',
    category: 'Grain',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '1 packet', multiplier: 1 }],
    nutrition: { calories: 100, protein: 4, carbs: 19, fats: 2, fiber: 3, sugar: 0, sodium: 75, saturatedFat: 0.3 },
    isVerified: true,
  },
  {
    name: 'Bread (white, 1 slice)',
    category: 'Grain',
    servingSize: 25,
    servingUnit: 'g',
    alternateServings: [{ label: '1 slice', multiplier: 1 }, { label: '2 slices', multiplier: 2 }],
    nutrition: { calories: 67, protein: 2, carbs: 13, fats: 0.8, fiber: 0.6, sugar: 1.4, sodium: 130, saturatedFat: 0.2 },
    isVerified: true,
  },
  {
    name: 'Bread (whole wheat, 1 slice)',
    category: 'Grain',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '1 slice', multiplier: 1 }, { label: '2 slices', multiplier: 2 }],
    nutrition: { calories: 69, protein: 3.6, carbs: 12, fats: 1, fiber: 1.9, sugar: 1.4, sodium: 132, saturatedFat: 0.2 },
    isVerified: true,
  },
  {
    name: 'Bagel (plain)',
    category: 'Grain',
    servingSize: 95,
    servingUnit: 'each',
    alternateServings: [{ label: '1 bagel', multiplier: 1 }],
    nutrition: { calories: 270, protein: 10, carbs: 53, fats: 1.5, fiber: 2, sugar: 5, sodium: 430, saturatedFat: 0.3 },
    isVerified: true,
  },
  {
    name: 'English Muffin',
    category: 'Grain',
    servingSize: 57,
    servingUnit: 'each',
    alternateServings: [{ label: '1 muffin', multiplier: 1 }],
    nutrition: { calories: 132, protein: 4.4, carbs: 26, fats: 1, fiber: 1.5, sugar: 2, sodium: 264, saturatedFat: 0.2 },
    isVerified: true,
  },
  {
    name: 'Flour Tortilla (8")',
    category: 'Grain',
    servingSize: 45,
    servingUnit: 'each',
    alternateServings: [{ label: '1 tortilla', multiplier: 1 }],
    nutrition: { calories: 140, protein: 3.5, carbs: 24, fats: 3.5, fiber: 1, sugar: 1, sodium: 350, saturatedFat: 1 },
    isVerified: true,
  },
  {
    name: 'Corn Tortilla (6")',
    category: 'Grain',
    servingSize: 26,
    servingUnit: 'each',
    alternateServings: [{ label: '1 tortilla', multiplier: 1 }, { label: '3 tortillas', multiplier: 3 }],
    nutrition: { calories: 52, protein: 1.4, carbs: 11, fats: 0.7, fiber: 1.5, sugar: 0.2, sodium: 11, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Pasta (regular, cooked)',
    category: 'Grain',
    servingSize: 140,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 220, protein: 8, carbs: 43, fats: 1.3, fiber: 2.5, sugar: 0.6, sodium: 1, saturatedFat: 0.2 },
    isVerified: true,
  },
  {
    name: 'Pasta (whole wheat, cooked)',
    category: 'Grain',
    servingSize: 140,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 174, protein: 7.5, carbs: 37, fats: 0.8, fiber: 6, sugar: 0.8, sodium: 4, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Sweet Potato (baked)',
    category: 'Grain',
    servingSize: 150,
    servingUnit: 'g',
    alternateServings: [{ label: '1 medium', multiplier: 1 }],
    nutrition: { calories: 135, protein: 3, carbs: 31, fats: 0.2, fiber: 4.5, sugar: 10, sodium: 55, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'White Potato (baked, with skin)',
    category: 'Grain',
    servingSize: 173,
    servingUnit: 'g',
    alternateServings: [{ label: '1 medium', multiplier: 1 }],
    nutrition: { calories: 161, protein: 4.3, carbs: 37, fats: 0.2, fiber: 3.8, sugar: 2, sodium: 17, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Corn on the Cob',
    category: 'Grain',
    servingSize: 90,
    servingUnit: 'each',
    alternateServings: [{ label: '1 ear', multiplier: 1 }],
    nutrition: { calories: 77, protein: 2.9, carbs: 17, fats: 1.1, fiber: 2.4, sugar: 5, sodium: 1, saturatedFat: 0.2 },
    isVerified: true,
  },
  {
    name: 'Jasmine Rice (cooked)',
    category: 'Grain',
    servingSize: 158,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 213, protein: 4.4, carbs: 47, fats: 0.3, fiber: 0.4, sugar: 0, sodium: 2, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Couscous (cooked)',
    category: 'Grain',
    servingSize: 157,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 176, protein: 6, carbs: 36, fats: 0.3, fiber: 2, sugar: 0.2, sodium: 8, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Granola',
    category: 'Grain',
    servingSize: 55,
    servingUnit: 'g',
    alternateServings: [{ label: '1/2 cup', multiplier: 1 }],
    nutrition: { calories: 260, protein: 6, carbs: 37, fats: 10, fiber: 3, sugar: 14, sodium: 85, saturatedFat: 1.5 },
    isVerified: true,
  },
  {
    name: 'Pancake (plain, 4")',
    category: 'Grain',
    servingSize: 38,
    servingUnit: 'each',
    alternateServings: [{ label: '1 pancake', multiplier: 1 }, { label: '3 pancakes', multiplier: 3 }],
    nutrition: { calories: 86, protein: 2.5, carbs: 11, fats: 3.5, fiber: 0.4, sugar: 2, sodium: 167, saturatedFat: 0.8 },
    isVerified: true,
  },
  {
    name: 'Waffle (frozen, standard)',
    category: 'Grain',
    servingSize: 35,
    servingUnit: 'each',
    alternateServings: [{ label: '1 waffle', multiplier: 1 }, { label: '2 waffles', multiplier: 2 }],
    nutrition: { calories: 95, protein: 2, carbs: 15, fats: 3, fiber: 0.5, sugar: 2, sodium: 230, saturatedFat: 0.5 },
    isVerified: true,
  },

  // ─────────────────────────────────────────────────────────
  //  FRUITS (~20 items)
  // ─────────────────────────────────────────────────────────
  {
    name: 'Banana',
    category: 'Fruit',
    servingSize: 118,
    servingUnit: 'g',
    alternateServings: [{ label: '1 medium', multiplier: 1 }],
    nutrition: { calories: 105, protein: 1.3, carbs: 27, fats: 0.4, fiber: 3.1, sugar: 14, sodium: 1, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Apple (medium)',
    category: 'Fruit',
    servingSize: 182,
    servingUnit: 'g',
    alternateServings: [{ label: '1 medium', multiplier: 1 }],
    nutrition: { calories: 95, protein: 0.5, carbs: 25, fats: 0.3, fiber: 4.4, sugar: 19, sodium: 2, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Orange (medium)',
    category: 'Fruit',
    servingSize: 131,
    servingUnit: 'g',
    alternateServings: [{ label: '1 medium', multiplier: 1 }],
    nutrition: { calories: 62, protein: 1.2, carbs: 15, fats: 0.2, fiber: 3.1, sugar: 12, sodium: 0, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Strawberries',
    category: 'Fruit',
    servingSize: 152,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup whole', multiplier: 1 }],
    nutrition: { calories: 49, protein: 1, carbs: 12, fats: 0.5, fiber: 3, sugar: 7, sodium: 1, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Blueberries',
    category: 'Fruit',
    servingSize: 148,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 84, protein: 1.1, carbs: 21, fats: 0.5, fiber: 3.6, sugar: 15, sodium: 1, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Raspberries',
    category: 'Fruit',
    servingSize: 123,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 64, protein: 1.5, carbs: 15, fats: 0.8, fiber: 8, sugar: 5.4, sodium: 1, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Grapes (seedless)',
    category: 'Fruit',
    servingSize: 151,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 104, protein: 1.1, carbs: 27, fats: 0.2, fiber: 1.4, sugar: 23, sodium: 3, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Watermelon (diced)',
    category: 'Fruit',
    servingSize: 152,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }, { label: '1 wedge', multiplier: 1.8 }],
    nutrition: { calories: 46, protein: 0.9, carbs: 11.5, fats: 0.2, fiber: 0.6, sugar: 9.4, sodium: 2, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Pineapple (chunks)',
    category: 'Fruit',
    servingSize: 165,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 82, protein: 0.9, carbs: 22, fats: 0.2, fiber: 2.3, sugar: 16, sodium: 2, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Mango (sliced)',
    category: 'Fruit',
    servingSize: 165,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }, { label: '1 whole mango', multiplier: 1.3 }],
    nutrition: { calories: 99, protein: 1.4, carbs: 25, fats: 0.6, fiber: 2.6, sugar: 23, sodium: 2, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Avocado',
    category: 'Fruit',
    servingSize: 68,
    servingUnit: 'g',
    alternateServings: [{ label: '1/2 avocado', multiplier: 1 }, { label: '1 whole', multiplier: 2 }],
    nutrition: { calories: 114, protein: 1.3, carbs: 6, fats: 10.5, fiber: 4.6, sugar: 0.2, sodium: 5, saturatedFat: 1.4 },
    isVerified: true,
  },
  {
    name: 'Dried Cranberries',
    category: 'Fruit',
    servingSize: 40,
    servingUnit: 'g',
    alternateServings: [{ label: '1/4 cup', multiplier: 1 }],
    nutrition: { calories: 123, protein: 0.1, carbs: 33, fats: 0.5, fiber: 2, sugar: 29, sodium: 2, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Raisins',
    category: 'Fruit',
    servingSize: 40,
    servingUnit: 'g',
    alternateServings: [{ label: '1 small box', multiplier: 1.06 }],
    nutrition: { calories: 120, protein: 1.3, carbs: 32, fats: 0.2, fiber: 1.6, sugar: 26, sodium: 4, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Dates (medjool)',
    category: 'Fruit',
    servingSize: 24,
    servingUnit: 'g',
    alternateServings: [{ label: '1 date', multiplier: 1 }, { label: '3 dates', multiplier: 3 }],
    nutrition: { calories: 66, protein: 0.4, carbs: 18, fats: 0, fiber: 1.6, sugar: 16, sodium: 0, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Peach (medium)',
    category: 'Fruit',
    servingSize: 150,
    servingUnit: 'g',
    alternateServings: [{ label: '1 medium', multiplier: 1 }],
    nutrition: { calories: 59, protein: 1.4, carbs: 14, fats: 0.4, fiber: 2.3, sugar: 13, sodium: 0, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Pear (medium)',
    category: 'Fruit',
    servingSize: 178,
    servingUnit: 'g',
    alternateServings: [{ label: '1 medium', multiplier: 1 }],
    nutrition: { calories: 101, protein: 0.6, carbs: 27, fats: 0.2, fiber: 5.5, sugar: 17, sodium: 2, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Cherries (sweet)',
    category: 'Fruit',
    servingSize: 138,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 87, protein: 1.5, carbs: 22, fats: 0.3, fiber: 2.9, sugar: 18, sodium: 0, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Cantaloupe (diced)',
    category: 'Fruit',
    servingSize: 160,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 54, protein: 1.3, carbs: 13, fats: 0.3, fiber: 1.4, sugar: 13, sodium: 25, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Kiwi (medium)',
    category: 'Fruit',
    servingSize: 69,
    servingUnit: 'g',
    alternateServings: [{ label: '1 kiwi', multiplier: 1 }, { label: '2 kiwis', multiplier: 2 }],
    nutrition: { calories: 42, protein: 0.8, carbs: 10, fats: 0.4, fiber: 2.1, sugar: 6, sodium: 2, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Frozen Mixed Berries',
    category: 'Fruit',
    servingSize: 140,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 70, protein: 1, carbs: 16, fats: 0.5, fiber: 4, sugar: 10, sodium: 1, saturatedFat: 0 },
    isVerified: true,
  },

  // ─────────────────────────────────────────────────────────
  //  VEGETABLES (~25 items)
  // ─────────────────────────────────────────────────────────
  {
    name: 'Broccoli (raw)',
    category: 'Vegetable',
    servingSize: 91,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup chopped', multiplier: 1 }],
    nutrition: { calories: 31, protein: 2.6, carbs: 6, fats: 0.3, fiber: 2.4, sugar: 1.6, sodium: 30, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Broccoli (steamed)',
    category: 'Vegetable',
    servingSize: 91,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 31, protein: 2.6, carbs: 6, fats: 0.4, fiber: 2.4, sugar: 1.6, sodium: 30, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Spinach (raw)',
    category: 'Vegetable',
    servingSize: 30,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }, { label: '2 cups (salad)', multiplier: 2 }],
    nutrition: { calories: 7, protein: 0.9, carbs: 1.1, fats: 0.1, fiber: 0.7, sugar: 0.1, sodium: 24, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Spinach (cooked)',
    category: 'Vegetable',
    servingSize: 180,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 41, protein: 5.3, carbs: 6.7, fats: 0.5, fiber: 4.3, sugar: 0.8, sodium: 126, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Kale (raw, chopped)',
    category: 'Vegetable',
    servingSize: 67,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 33, protein: 2.2, carbs: 6, fats: 0.6, fiber: 1.3, sugar: 0, sodium: 25, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Romaine Lettuce',
    category: 'Vegetable',
    servingSize: 47,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup shredded', multiplier: 1 }, { label: '3 cups (salad base)', multiplier: 3 }],
    nutrition: { calories: 8, protein: 0.6, carbs: 1.5, fats: 0.1, fiber: 1, sugar: 0.6, sodium: 4, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Iceberg Lettuce',
    category: 'Vegetable',
    servingSize: 72,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup shredded', multiplier: 1 }],
    nutrition: { calories: 10, protein: 0.6, carbs: 2.1, fats: 0.1, fiber: 0.9, sugar: 1.4, sodium: 7, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Bell Pepper (red)',
    category: 'Vegetable',
    servingSize: 149,
    servingUnit: 'g',
    alternateServings: [{ label: '1 medium', multiplier: 1 }, { label: '1 cup chopped', multiplier: 1 }],
    nutrition: { calories: 46, protein: 1.5, carbs: 9, fats: 0.4, fiber: 3.1, sugar: 6.3, sodium: 6, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Bell Pepper (green)',
    category: 'Vegetable',
    servingSize: 149,
    servingUnit: 'g',
    alternateServings: [{ label: '1 medium', multiplier: 1 }],
    nutrition: { calories: 30, protein: 1.3, carbs: 7, fats: 0.2, fiber: 2.5, sugar: 3.5, sodium: 4, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Tomato',
    category: 'Vegetable',
    servingSize: 123,
    servingUnit: 'g',
    alternateServings: [{ label: '1 medium', multiplier: 1 }, { label: '1 cup chopped', multiplier: 1.5 }],
    nutrition: { calories: 22, protein: 1.1, carbs: 4.8, fats: 0.2, fiber: 1.5, sugar: 3.2, sodium: 6, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Cherry Tomatoes',
    category: 'Vegetable',
    servingSize: 149,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 27, protein: 1.3, carbs: 5.8, fats: 0.3, fiber: 1.8, sugar: 3.9, sodium: 7, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Cucumber (sliced)',
    category: 'Vegetable',
    servingSize: 119,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }, { label: '1/2 cucumber', multiplier: 1.3 }],
    nutrition: { calories: 16, protein: 0.7, carbs: 3, fats: 0.2, fiber: 0.5, sugar: 1.7, sodium: 2, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Onion (chopped)',
    category: 'Vegetable',
    servingSize: 115,
    servingUnit: 'g',
    alternateServings: [{ label: '1 medium', multiplier: 1 }, { label: '1/2 cup', multiplier: 0.7 }],
    nutrition: { calories: 46, protein: 1.3, carbs: 11, fats: 0.1, fiber: 1.9, sugar: 5, sodium: 5, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Garlic (clove)',
    category: 'Vegetable',
    servingSize: 3,
    servingUnit: 'g',
    alternateServings: [{ label: '1 clove', multiplier: 1 }, { label: '3 cloves', multiplier: 3 }],
    nutrition: { calories: 4, protein: 0.2, carbs: 1, fats: 0, fiber: 0.1, sugar: 0, sodium: 1, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Carrots (raw, chopped)',
    category: 'Vegetable',
    servingSize: 128,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }, { label: '1 medium carrot', multiplier: 0.48 }],
    nutrition: { calories: 52, protein: 1.2, carbs: 12, fats: 0.3, fiber: 3.6, sugar: 6, sodium: 88, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Celery (stalk)',
    category: 'Vegetable',
    servingSize: 40,
    servingUnit: 'g',
    alternateServings: [{ label: '1 stalk', multiplier: 1 }, { label: '2 stalks', multiplier: 2 }],
    nutrition: { calories: 6, protein: 0.3, carbs: 1.2, fats: 0.1, fiber: 0.6, sugar: 0.5, sodium: 32, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Mushrooms (white, sliced)',
    category: 'Vegetable',
    servingSize: 70,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 15, protein: 2.2, carbs: 2.3, fats: 0.2, fiber: 0.7, sugar: 1.4, sodium: 4, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Zucchini (sliced)',
    category: 'Vegetable',
    servingSize: 113,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }, { label: '1 medium', multiplier: 1.7 }],
    nutrition: { calories: 19, protein: 1.4, carbs: 3.5, fats: 0.4, fiber: 1.1, sugar: 2.8, sodium: 9, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Asparagus',
    category: 'Vegetable',
    servingSize: 134,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }, { label: '5 spears', multiplier: 0.5 }],
    nutrition: { calories: 27, protein: 2.9, carbs: 5.2, fats: 0.2, fiber: 2.8, sugar: 2.5, sodium: 3, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Green Beans',
    category: 'Vegetable',
    servingSize: 125,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 34, protein: 2, carbs: 7.8, fats: 0.1, fiber: 3.4, sugar: 1.5, sodium: 6, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Peas (green, cooked)',
    category: 'Vegetable',
    servingSize: 160,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 134, protein: 8.6, carbs: 25, fats: 0.4, fiber: 8.8, sugar: 9.5, sodium: 5, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Cauliflower (raw)',
    category: 'Vegetable',
    servingSize: 107,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 27, protein: 2, carbs: 5, fats: 0.3, fiber: 2.1, sugar: 2, sodium: 32, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Cabbage (shredded)',
    category: 'Vegetable',
    servingSize: 89,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 22, protein: 1.1, carbs: 5.2, fats: 0.1, fiber: 2.2, sugar: 2.8, sodium: 16, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Brussels Sprouts (cooked)',
    category: 'Vegetable',
    servingSize: 156,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 56, protein: 4, carbs: 11, fats: 0.8, fiber: 4.1, sugar: 2.7, sodium: 16, saturatedFat: 0.2 },
    isVerified: true,
  },
  {
    name: 'Mixed Salad Greens',
    category: 'Vegetable',
    servingSize: 85,
    servingUnit: 'g',
    alternateServings: [{ label: '3 cups (salad base)', multiplier: 1 }],
    nutrition: { calories: 15, protein: 1.5, carbs: 2.5, fats: 0.2, fiber: 1.5, sugar: 0.5, sodium: 25, saturatedFat: 0 },
    isVerified: true,
  },

  // ─────────────────────────────────────────────────────────
  //  FATS & NUTS (~15 items)
  // ─────────────────────────────────────────────────────────
  {
    name: 'Olive Oil',
    category: 'Fat',
    servingSize: 14,
    servingUnit: 'tbsp',
    alternateServings: [{ label: '1 tbsp', multiplier: 1 }, { label: '1 tsp', multiplier: 0.33 }],
    nutrition: { calories: 119, protein: 0, carbs: 0, fats: 14, fiber: 0, sugar: 0, sodium: 0, saturatedFat: 1.9 },
    isVerified: true,
  },
  {
    name: 'Coconut Oil',
    category: 'Fat',
    servingSize: 14,
    servingUnit: 'tbsp',
    alternateServings: [{ label: '1 tbsp', multiplier: 1 }],
    nutrition: { calories: 121, protein: 0, carbs: 0, fats: 14, fiber: 0, sugar: 0, sodium: 0, saturatedFat: 12 },
    isVerified: true,
  },
  {
    name: 'Avocado Oil',
    category: 'Fat',
    servingSize: 14,
    servingUnit: 'tbsp',
    alternateServings: [{ label: '1 tbsp', multiplier: 1 }],
    nutrition: { calories: 124, protein: 0, carbs: 0, fats: 14, fiber: 0, sugar: 0, sodium: 0, saturatedFat: 1.6 },
    isVerified: true,
  },
  {
    name: 'Peanut Butter',
    category: 'Fat',
    servingSize: 32,
    servingUnit: 'g',
    alternateServings: [{ label: '2 tbsp', multiplier: 1 }, { label: '1 tbsp', multiplier: 0.5 }],
    nutrition: { calories: 190, protein: 7, carbs: 7, fats: 16, fiber: 2, sugar: 3, sodium: 136, saturatedFat: 3 },
    isVerified: true,
  },
  {
    name: 'Almond Butter',
    category: 'Fat',
    servingSize: 32,
    servingUnit: 'g',
    alternateServings: [{ label: '2 tbsp', multiplier: 1 }, { label: '1 tbsp', multiplier: 0.5 }],
    nutrition: { calories: 196, protein: 7, carbs: 6, fats: 18, fiber: 3.3, sugar: 2, sodium: 2, saturatedFat: 1.4 },
    isVerified: true,
  },
  {
    name: 'Almonds',
    category: 'Fat',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '~23 almonds', multiplier: 1 }, { label: '1/4 cup', multiplier: 1.25 }],
    nutrition: { calories: 164, protein: 6, carbs: 6, fats: 14, fiber: 3.5, sugar: 1.2, sodium: 0, saturatedFat: 1.1 },
    isVerified: true,
  },
  {
    name: 'Walnuts (halves)',
    category: 'Fat',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '~14 halves', multiplier: 1 }, { label: '1/4 cup', multiplier: 1.1 }],
    nutrition: { calories: 185, protein: 4.3, carbs: 3.9, fats: 18.5, fiber: 1.9, sugar: 0.7, sodium: 1, saturatedFat: 1.7 },
    isVerified: true,
  },
  {
    name: 'Cashews',
    category: 'Fat',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '~18 cashews', multiplier: 1 }],
    nutrition: { calories: 157, protein: 5, carbs: 9, fats: 12, fiber: 0.9, sugar: 1.7, sodium: 3, saturatedFat: 2.2 },
    isVerified: true,
  },
  {
    name: 'Peanuts (dry roasted)',
    category: 'Fat',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '~28 peanuts', multiplier: 1 }, { label: '1/4 cup', multiplier: 1.3 }],
    nutrition: { calories: 166, protein: 7, carbs: 6, fats: 14, fiber: 2.3, sugar: 1, sodium: 2, saturatedFat: 1.9 },
    isVerified: true,
  },
  {
    name: 'Chia Seeds',
    category: 'Fat',
    servingSize: 12,
    servingUnit: 'g',
    alternateServings: [{ label: '1 tbsp', multiplier: 1 }, { label: '2 tbsp', multiplier: 2 }],
    nutrition: { calories: 58, protein: 2, carbs: 5, fats: 3.7, fiber: 4.1, sugar: 0, sodium: 2, saturatedFat: 0.4 },
    isVerified: true,
  },
  {
    name: 'Flax Seeds (ground)',
    category: 'Fat',
    servingSize: 7,
    servingUnit: 'g',
    alternateServings: [{ label: '1 tbsp', multiplier: 1 }, { label: '2 tbsp', multiplier: 2 }],
    nutrition: { calories: 37, protein: 1.3, carbs: 2, fats: 3, fiber: 1.9, sugar: 0.1, sodium: 2, saturatedFat: 0.3 },
    isVerified: true,
  },
  {
    name: 'Dark Chocolate (70%+)',
    category: 'Fat',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '1 oz / 2 squares', multiplier: 1 }],
    nutrition: { calories: 170, protein: 2, carbs: 13, fats: 12, fiber: 3, sugar: 7, sodium: 6, saturatedFat: 7 },
    isVerified: true,
  },
  {
    name: 'Pecans',
    category: 'Fat',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '~19 halves', multiplier: 1 }],
    nutrition: { calories: 196, protein: 2.6, carbs: 3.9, fats: 20, fiber: 2.7, sugar: 1.1, sodium: 0, saturatedFat: 1.7 },
    isVerified: true,
  },
  {
    name: 'Sunflower Seeds (shelled)',
    category: 'Fat',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '1/4 cup', multiplier: 1 }],
    nutrition: { calories: 165, protein: 5.5, carbs: 7, fats: 14, fiber: 3, sugar: 0.8, sodium: 1, saturatedFat: 1.5 },
    isVerified: true,
  },
  {
    name: 'Pumpkin Seeds (shelled)',
    category: 'Fat',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '1/4 cup', multiplier: 1 }],
    nutrition: { calories: 153, protein: 7, carbs: 5, fats: 13, fiber: 1.7, sugar: 0.3, sodium: 5, saturatedFat: 2.3 },
    isVerified: true,
  },

  // ─────────────────────────────────────────────────────────
  //  BEVERAGES (~10 items)
  // ─────────────────────────────────────────────────────────
  {
    name: 'Black Coffee',
    category: 'Beverage',
    servingSize: 240,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 cup (8 oz)', multiplier: 1 }, { label: '12 oz mug', multiplier: 1.5 }],
    nutrition: { calories: 2, protein: 0.3, carbs: 0, fats: 0, fiber: 0, sugar: 0, sodium: 5, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Green Tea',
    category: 'Beverage',
    servingSize: 240,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 2, protein: 0.5, carbs: 0, fats: 0, fiber: 0, sugar: 0, sodium: 7, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Orange Juice',
    category: 'Beverage',
    servingSize: 240,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 cup', multiplier: 1 }, { label: '1 glass (12 oz)', multiplier: 1.5 }],
    nutrition: { calories: 112, protein: 1.7, carbs: 26, fats: 0.5, fiber: 0.5, sugar: 21, sodium: 2, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Apple Juice',
    category: 'Beverage',
    servingSize: 240,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 114, protein: 0.3, carbs: 28, fats: 0.3, fiber: 0.5, sugar: 24, sodium: 10, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Protein Shake (generic, mixed)',
    category: 'Beverage',
    servingSize: 350,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 shake', multiplier: 1 }],
    nutrition: { calories: 160, protein: 30, carbs: 6, fats: 2, fiber: 1, sugar: 2, sodium: 200, saturatedFat: 0.5 },
    isVerified: true,
  },
  {
    name: 'Coconut Water',
    category: 'Beverage',
    servingSize: 240,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 46, protein: 1.7, carbs: 9, fats: 0.5, fiber: 2.6, sugar: 6, sodium: 252, saturatedFat: 0.4 },
    isVerified: true,
  },
  {
    name: 'Soda (Cola)',
    category: 'Beverage',
    servingSize: 355,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 can (12 oz)', multiplier: 1 }, { label: '20 oz bottle', multiplier: 1.69 }],
    nutrition: { calories: 140, protein: 0, carbs: 39, fats: 0, fiber: 0, sugar: 39, sodium: 45, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Beer (regular)',
    category: 'Beverage',
    servingSize: 355,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 can/bottle (12 oz)', multiplier: 1 }],
    nutrition: { calories: 153, protein: 1.6, carbs: 13, fats: 0, fiber: 0, sugar: 0, sodium: 14, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Red Wine',
    category: 'Beverage',
    servingSize: 148,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 glass (5 oz)', multiplier: 1 }],
    nutrition: { calories: 125, protein: 0.1, carbs: 3.8, fats: 0, fiber: 0, sugar: 0.9, sodium: 6, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Lemonade',
    category: 'Beverage',
    servingSize: 240,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 99, protein: 0.2, carbs: 26, fats: 0.1, fiber: 0.2, sugar: 25, sodium: 7, saturatedFat: 0 },
    isVerified: true,
  },

  // ─────────────────────────────────────────────────────────
  //  CONDIMENTS & SAUCES (~15 items)
  // ─────────────────────────────────────────────────────────
  {
    name: 'Ketchup',
    category: 'Condiment',
    servingSize: 17,
    servingUnit: 'g',
    alternateServings: [{ label: '1 tbsp', multiplier: 1 }, { label: '1 packet', multiplier: 0.6 }],
    nutrition: { calories: 20, protein: 0.2, carbs: 5, fats: 0, fiber: 0, sugar: 4, sodium: 160, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Yellow Mustard',
    category: 'Condiment',
    servingSize: 5,
    servingUnit: 'g',
    alternateServings: [{ label: '1 tsp', multiplier: 1 }, { label: '1 tbsp', multiplier: 3 }],
    nutrition: { calories: 3, protein: 0.2, carbs: 0.3, fats: 0.2, fiber: 0.2, sugar: 0.1, sodium: 56, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Mayonnaise',
    category: 'Condiment',
    servingSize: 13,
    servingUnit: 'g',
    alternateServings: [{ label: '1 tbsp', multiplier: 1 }],
    nutrition: { calories: 94, protein: 0.1, carbs: 0, fats: 10, fiber: 0, sugar: 0, sodium: 88, saturatedFat: 1.6 },
    isVerified: true,
  },
  {
    name: 'Soy Sauce',
    category: 'Condiment',
    servingSize: 15,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 tbsp', multiplier: 1 }],
    nutrition: { calories: 9, protein: 0.9, carbs: 1, fats: 0, fiber: 0, sugar: 0.1, sodium: 879, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Hot Sauce',
    category: 'Condiment',
    servingSize: 5,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 tsp', multiplier: 1 }, { label: '1 tbsp', multiplier: 3 }],
    nutrition: { calories: 1, protein: 0, carbs: 0, fats: 0, fiber: 0, sugar: 0, sodium: 124, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Honey',
    category: 'Condiment',
    servingSize: 21,
    servingUnit: 'g',
    alternateServings: [{ label: '1 tbsp', multiplier: 1 }],
    nutrition: { calories: 64, protein: 0.1, carbs: 17, fats: 0, fiber: 0, sugar: 17, sodium: 1, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Maple Syrup',
    category: 'Condiment',
    servingSize: 20,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 tbsp', multiplier: 1 }, { label: '1/4 cup', multiplier: 4 }],
    nutrition: { calories: 52, protein: 0, carbs: 13, fats: 0, fiber: 0, sugar: 12, sodium: 2, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Sugar (granulated)',
    category: 'Condiment',
    servingSize: 4,
    servingUnit: 'g',
    alternateServings: [{ label: '1 tsp', multiplier: 1 }, { label: '1 tbsp', multiplier: 3 }],
    nutrition: { calories: 16, protein: 0, carbs: 4, fats: 0, fiber: 0, sugar: 4, sodium: 0, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Salsa',
    category: 'Condiment',
    servingSize: 30,
    servingUnit: 'g',
    alternateServings: [{ label: '2 tbsp', multiplier: 1 }, { label: '1/4 cup', multiplier: 2 }],
    nutrition: { calories: 10, protein: 0.5, carbs: 2, fats: 0, fiber: 0.5, sugar: 1.5, sodium: 220, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Hummus',
    category: 'Condiment',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '2 tbsp', multiplier: 1 }, { label: '1/3 cup', multiplier: 2.7 }],
    nutrition: { calories: 50, protein: 2, carbs: 4, fats: 3, fiber: 1, sugar: 0, sodium: 115, saturatedFat: 0.4 },
    isVerified: true,
  },
  {
    name: 'Guacamole',
    category: 'Condiment',
    servingSize: 30,
    servingUnit: 'g',
    alternateServings: [{ label: '2 tbsp', multiplier: 1 }],
    nutrition: { calories: 50, protein: 0.6, carbs: 3, fats: 4.5, fiber: 2, sugar: 0.3, sodium: 115, saturatedFat: 0.6 },
    isVerified: true,
  },
  {
    name: 'Ranch Dressing',
    category: 'Condiment',
    servingSize: 30,
    servingUnit: 'g',
    alternateServings: [{ label: '2 tbsp', multiplier: 1 }],
    nutrition: { calories: 129, protein: 0.4, carbs: 2, fats: 13, fiber: 0, sugar: 1, sodium: 270, saturatedFat: 2 },
    isVerified: true,
  },
  {
    name: 'Italian Dressing',
    category: 'Condiment',
    servingSize: 30,
    servingUnit: 'g',
    alternateServings: [{ label: '2 tbsp', multiplier: 1 }],
    nutrition: { calories: 70, protein: 0.1, carbs: 3, fats: 6, fiber: 0, sugar: 2.5, sodium: 310, saturatedFat: 0.9 },
    isVerified: true,
  },
  {
    name: 'Balsamic Vinegar',
    category: 'Condiment',
    servingSize: 15,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 tbsp', multiplier: 1 }],
    nutrition: { calories: 14, protein: 0.1, carbs: 2.7, fats: 0, fiber: 0, sugar: 2.4, sodium: 4, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'BBQ Sauce',
    category: 'Condiment',
    servingSize: 34,
    servingUnit: 'g',
    alternateServings: [{ label: '2 tbsp', multiplier: 1 }],
    nutrition: { calories: 52, protein: 0.2, carbs: 13, fats: 0.1, fiber: 0.2, sugar: 10, sodium: 326, saturatedFat: 0 },
    isVerified: true,
  },

  // ─────────────────────────────────────────────────────────
  //  SNACKS (~15 items)
  // ─────────────────────────────────────────────────────────
  {
    name: 'Protein Bar (generic)',
    category: 'Snack',
    servingSize: 60,
    servingUnit: 'each',
    alternateServings: [{ label: '1 bar', multiplier: 1 }],
    nutrition: { calories: 210, protein: 20, carbs: 22, fats: 7, fiber: 4, sugar: 5, sodium: 170, saturatedFat: 3.5 },
    isVerified: true,
  },
  {
    name: 'Granola Bar',
    category: 'Snack',
    servingSize: 42,
    servingUnit: 'each',
    alternateServings: [{ label: '1 bar', multiplier: 1 }],
    nutrition: { calories: 190, protein: 3, carbs: 29, fats: 7, fiber: 2, sugar: 12, sodium: 160, saturatedFat: 1 },
    isVerified: true,
  },
  {
    name: 'Rice Cakes (plain)',
    category: 'Snack',
    servingSize: 9,
    servingUnit: 'each',
    alternateServings: [{ label: '1 cake', multiplier: 1 }, { label: '2 cakes', multiplier: 2 }],
    nutrition: { calories: 35, protein: 0.7, carbs: 7, fats: 0.3, fiber: 0.4, sugar: 0, sodium: 29, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Popcorn (air-popped)',
    category: 'Snack',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '3 cups popped', multiplier: 1 }],
    nutrition: { calories: 110, protein: 3, carbs: 22, fats: 1.3, fiber: 4, sugar: 0, sodium: 1, saturatedFat: 0.2 },
    isVerified: true,
  },
  {
    name: 'Pretzels',
    category: 'Snack',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '~17 twists', multiplier: 1 }],
    nutrition: { calories: 108, protein: 3, carbs: 23, fats: 0.5, fiber: 0.9, sugar: 0.6, sodium: 352, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Trail Mix',
    category: 'Snack',
    servingSize: 40,
    servingUnit: 'g',
    alternateServings: [{ label: '1/4 cup', multiplier: 1 }],
    nutrition: { calories: 173, protein: 5, carbs: 17, fats: 11, fiber: 2, sugar: 9, sodium: 65, saturatedFat: 2.1 },
    isVerified: true,
  },
  {
    name: 'Tortilla Chips',
    category: 'Snack',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '~10 chips', multiplier: 1 }],
    nutrition: { calories: 140, protein: 2, carbs: 19, fats: 7, fiber: 1, sugar: 0.3, sodium: 115, saturatedFat: 1 },
    isVerified: true,
  },
  {
    name: 'Saltine Crackers',
    category: 'Snack',
    servingSize: 16,
    servingUnit: 'g',
    alternateServings: [{ label: '5 crackers', multiplier: 1 }],
    nutrition: { calories: 70, protein: 1, carbs: 12, fats: 1.5, fiber: 0, sugar: 0, sodium: 150, saturatedFat: 0.3 },
    isVerified: true,
  },
  {
    name: 'Beef Jerky',
    category: 'Snack',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '1 oz serving', multiplier: 1 }],
    nutrition: { calories: 82, protein: 14, carbs: 3, fats: 1, fiber: 0.4, sugar: 3, sodium: 418, saturatedFat: 0.4 },
    isVerified: true,
  },
  {
    name: 'Peanut Butter Crackers (6 pack)',
    category: 'Snack',
    servingSize: 39,
    servingUnit: 'each',
    alternateServings: [{ label: '1 pack', multiplier: 1 }],
    nutrition: { calories: 190, protein: 5, carbs: 22, fats: 10, fiber: 1, sugar: 4, sodium: 290, saturatedFat: 2 },
    isVerified: true,
  },
  {
    name: 'Mixed Nuts (roasted)',
    category: 'Snack',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '~20 pieces', multiplier: 1 }],
    nutrition: { calories: 172, protein: 5, carbs: 7, fats: 15, fiber: 2, sugar: 1.5, sodium: 96, saturatedFat: 2 },
    isVerified: true,
  },
  {
    name: 'Chips (potato, regular)',
    category: 'Snack',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '~15 chips', multiplier: 1 }],
    nutrition: { calories: 152, protein: 2, carbs: 15, fats: 10, fiber: 1.2, sugar: 0.1, sodium: 168, saturatedFat: 1.5 },
    isVerified: true,
  },
  {
    name: 'Dark Chocolate Almonds',
    category: 'Snack',
    servingSize: 40,
    servingUnit: 'g',
    alternateServings: [{ label: '1/4 cup', multiplier: 1 }],
    nutrition: { calories: 210, protein: 4, carbs: 18, fats: 15, fiber: 3, sugar: 13, sodium: 10, saturatedFat: 5 },
    isVerified: true,
  },
  {
    name: 'Fruit Snacks (pouch)',
    category: 'Snack',
    servingSize: 25,
    servingUnit: 'each',
    alternateServings: [{ label: '1 pouch', multiplier: 1 }],
    nutrition: { calories: 80, protein: 0, carbs: 20, fats: 0, fiber: 0, sugar: 11, sodium: 15, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Goldfish Crackers',
    category: 'Snack',
    servingSize: 30,
    servingUnit: 'g',
    alternateServings: [{ label: '~55 crackers', multiplier: 1 }],
    nutrition: { calories: 140, protein: 3, carbs: 20, fats: 5, fiber: 1, sugar: 0, sodium: 250, saturatedFat: 1 },
    isVerified: true,
  },

  // ─────────────────────────────────────────────────────────
  //  FAST FOOD / COMMON MEALS (~15 items)
  // ─────────────────────────────────────────────────────────
  {
    name: 'Chipotle Burrito Bowl (chicken)',
    brand: 'Chipotle',
    category: 'Other',
    servingSize: 510,
    servingUnit: 'g',
    alternateServings: [{ label: '1 bowl', multiplier: 1 }],
    nutrition: { calories: 665, protein: 53, carbs: 56, fats: 23, fiber: 14, sugar: 5, sodium: 1960, saturatedFat: 8 },
    isVerified: true,
  },
  {
    name: 'Subway 6" Turkey Sub',
    brand: 'Subway',
    category: 'Other',
    servingSize: 230,
    servingUnit: 'g',
    alternateServings: [{ label: '1 sub', multiplier: 1 }],
    nutrition: { calories: 280, protein: 18, carbs: 46, fats: 3.5, fiber: 5, sugar: 7, sodium: 810, saturatedFat: 1 },
    isVerified: true,
  },
  {
    name: 'Pizza Slice (cheese, thin crust)',
    category: 'Other',
    servingSize: 107,
    servingUnit: 'slice',
    alternateServings: [{ label: '1 slice', multiplier: 1 }, { label: '2 slices', multiplier: 2 }],
    nutrition: { calories: 272, protein: 12, carbs: 34, fats: 10, fiber: 2, sugar: 4, sodium: 551, saturatedFat: 4.4 },
    isVerified: true,
  },
  {
    name: 'Hamburger (generic, single patty)',
    category: 'Other',
    servingSize: 215,
    servingUnit: 'each',
    alternateServings: [{ label: '1 burger', multiplier: 1 }],
    nutrition: { calories: 540, protein: 34, carbs: 40, fats: 27, fiber: 2, sugar: 8, sodium: 790, saturatedFat: 10 },
    isVerified: true,
  },
  {
    name: 'French Fries (medium)',
    category: 'Other',
    servingSize: 117,
    servingUnit: 'g',
    alternateServings: [{ label: '1 medium order', multiplier: 1 }],
    nutrition: { calories: 365, protein: 4, carbs: 48, fats: 17, fiber: 4, sugar: 0.3, sodium: 246, saturatedFat: 2.3 },
    isVerified: true,
  },
  {
    name: 'Chick-fil-A Chicken Sandwich',
    brand: 'Chick-fil-A',
    category: 'Other',
    servingSize: 200,
    servingUnit: 'each',
    alternateServings: [{ label: '1 sandwich', multiplier: 1 }],
    nutrition: { calories: 440, protein: 28, carbs: 40, fats: 19, fiber: 1, sugar: 6, sodium: 1350, saturatedFat: 4 },
    isVerified: true,
  },
  {
    name: "McDonald's Big Mac",
    brand: "McDonald's",
    category: 'Other',
    servingSize: 200,
    servingUnit: 'each',
    alternateServings: [{ label: '1 burger', multiplier: 1 }],
    nutrition: { calories: 550, protein: 25, carbs: 45, fats: 30, fiber: 3, sugar: 9, sodium: 1010, saturatedFat: 11 },
    isVerified: true,
  },
  {
    name: 'Chick-fil-A Nuggets (8 ct)',
    brand: 'Chick-fil-A',
    category: 'Other',
    servingSize: 113,
    servingUnit: 'each',
    alternateServings: [{ label: '8 nuggets', multiplier: 1 }, { label: '12 nuggets', multiplier: 1.5 }],
    nutrition: { calories: 260, protein: 27, carbs: 11, fats: 12, fiber: 0, sugar: 1, sodium: 1000, saturatedFat: 2.5 },
    isVerified: true,
  },
  {
    name: 'Taco (beef, hard shell)',
    category: 'Other',
    servingSize: 78,
    servingUnit: 'each',
    alternateServings: [{ label: '1 taco', multiplier: 1 }, { label: '3 tacos', multiplier: 3 }],
    nutrition: { calories: 156, protein: 8, carbs: 14, fats: 7, fiber: 2, sugar: 1, sodium: 274, saturatedFat: 2.8 },
    isVerified: true,
  },
  {
    name: 'Grilled Chicken Salad (no dressing)',
    category: 'Other',
    servingSize: 320,
    servingUnit: 'g',
    alternateServings: [{ label: '1 salad', multiplier: 1 }],
    nutrition: { calories: 230, protein: 33, carbs: 10, fats: 7, fiber: 4, sugar: 4, sodium: 450, saturatedFat: 2 },
    isVerified: true,
  },
  {
    name: 'Sushi Roll (California, 8 pcs)',
    category: 'Other',
    servingSize: 220,
    servingUnit: 'g',
    alternateServings: [{ label: '1 roll (8 pcs)', multiplier: 1 }],
    nutrition: { calories: 255, protein: 9, carbs: 38, fats: 7, fiber: 2.5, sugar: 6, sodium: 540, saturatedFat: 1 },
    isVerified: true,
  },
  {
    name: 'Chicken Quesadilla',
    category: 'Other',
    servingSize: 180,
    servingUnit: 'each',
    alternateServings: [{ label: '1 quesadilla', multiplier: 1 }],
    nutrition: { calories: 490, protein: 28, carbs: 37, fats: 25, fiber: 2, sugar: 2, sodium: 1000, saturatedFat: 11 },
    isVerified: true,
  },
  {
    name: 'PB&J Sandwich',
    category: 'Other',
    servingSize: 115,
    servingUnit: 'each',
    alternateServings: [{ label: '1 sandwich', multiplier: 1 }],
    nutrition: { calories: 376, protein: 13, carbs: 50, fats: 15, fiber: 3, sugar: 18, sodium: 420, saturatedFat: 3 },
    isVerified: true,
  },
  {
    name: 'Scrambled Eggs (2 eggs w/ butter)',
    category: 'Other',
    servingSize: 120,
    servingUnit: 'g',
    alternateServings: [{ label: '2-egg serving', multiplier: 1 }],
    nutrition: { calories: 182, protein: 12, carbs: 2, fats: 14, fiber: 0, sugar: 1, sodium: 300, saturatedFat: 5.5 },
    isVerified: true,
  },
  {
    name: 'Overnight Oats (basic)',
    category: 'Other',
    servingSize: 250,
    servingUnit: 'g',
    alternateServings: [{ label: '1 jar', multiplier: 1 }],
    nutrition: { calories: 300, protein: 12, carbs: 43, fats: 8, fiber: 5, sugar: 12, sodium: 80, saturatedFat: 1.5 },
    isVerified: true,
  },
  {
    name: 'Acai Bowl (medium)',
    category: 'Other',
    servingSize: 350,
    servingUnit: 'g',
    alternateServings: [{ label: '1 bowl', multiplier: 1 }],
    nutrition: { calories: 490, protein: 8, carbs: 76, fats: 18, fiber: 9, sugar: 55, sodium: 30, saturatedFat: 4 },
    isVerified: true,
  },

  // ─────────────────────────────────────────────────────────
  //  ADDITIONAL ITEMS (to reach 200+)
  // ─────────────────────────────────────────────────────────
  {
    name: 'Feta Cheese (crumbled)',
    category: 'Dairy',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '1/4 cup', multiplier: 1.3 }],
    nutrition: { calories: 75, protein: 4, carbs: 1.1, fats: 6, fiber: 0, sugar: 1.1, sodium: 316, saturatedFat: 4.2 },
    isVerified: true,
  },
  {
    name: 'Swiss Cheese',
    category: 'Dairy',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '1 slice', multiplier: 0.75 }],
    nutrition: { calories: 108, protein: 7.6, carbs: 1.5, fats: 8, fiber: 0, sugar: 0.4, sodium: 54, saturatedFat: 5 },
    isVerified: true,
  },
  {
    name: 'Provolone Cheese',
    category: 'Dairy',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '1 slice', multiplier: 0.75 }],
    nutrition: { calories: 98, protein: 7.3, carbs: 0.6, fats: 7.5, fiber: 0, sugar: 0.2, sodium: 248, saturatedFat: 4.8 },
    isVerified: true,
  },
  {
    name: 'Ginger (fresh, grated)',
    category: 'Vegetable',
    servingSize: 5,
    servingUnit: 'g',
    alternateServings: [{ label: '1 tsp', multiplier: 1 }, { label: '1 tbsp', multiplier: 3 }],
    nutrition: { calories: 4, protein: 0.1, carbs: 0.9, fats: 0, fiber: 0.1, sugar: 0.1, sodium: 1, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Jalapeño Pepper',
    category: 'Vegetable',
    servingSize: 14,
    servingUnit: 'g',
    alternateServings: [{ label: '1 pepper', multiplier: 1 }],
    nutrition: { calories: 4, protein: 0.1, carbs: 0.9, fats: 0, fiber: 0.4, sugar: 0.6, sodium: 0, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Sweet Corn (canned, drained)',
    category: 'Vegetable',
    servingSize: 125,
    servingUnit: 'g',
    alternateServings: [{ label: '1/2 cup', multiplier: 1 }],
    nutrition: { calories: 82, protein: 2.5, carbs: 20, fats: 0.5, fiber: 2, sugar: 5, sodium: 285, saturatedFat: 0.1 },
    isVerified: true,
  },
  {
    name: 'Teriyaki Sauce',
    category: 'Condiment',
    servingSize: 15,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 tbsp', multiplier: 1 }],
    nutrition: { calories: 16, protein: 1, carbs: 3, fats: 0, fiber: 0, sugar: 2.5, sodium: 610, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Sriracha',
    category: 'Condiment',
    servingSize: 5,
    servingUnit: 'g',
    alternateServings: [{ label: '1 tsp', multiplier: 1 }],
    nutrition: { calories: 5, protein: 0, carbs: 1, fats: 0, fiber: 0, sugar: 1, sodium: 80, saturatedFat: 0 },
    isVerified: true,
  },
  {
    name: 'Pesto (basil)',
    category: 'Condiment',
    servingSize: 28,
    servingUnit: 'g',
    alternateServings: [{ label: '2 tbsp', multiplier: 1 }],
    nutrition: { calories: 120, protein: 3, carbs: 2, fats: 11, fiber: 0.5, sugar: 0.5, sodium: 310, saturatedFat: 3 },
    isVerified: true,
  },
  {
    name: 'Mashed Potatoes (prepared)',
    category: 'Grain',
    servingSize: 210,
    servingUnit: 'g',
    alternateServings: [{ label: '1 cup', multiplier: 1 }],
    nutrition: { calories: 237, protein: 4, carbs: 35, fats: 9, fiber: 3, sugar: 3, sodium: 666, saturatedFat: 5.6 },
    isVerified: true,
  },
  {
    name: "McDonald's Egg McMuffin",
    brand: "McDonald's",
    category: 'Other',
    servingSize: 137,
    servingUnit: 'each',
    alternateServings: [{ label: '1 sandwich', multiplier: 1 }],
    nutrition: { calories: 310, protein: 17, carbs: 30, fats: 13, fiber: 2, sugar: 3, sodium: 750, saturatedFat: 6 },
    isVerified: true,
  },
  {
    name: 'Banana Protein Smoothie',
    category: 'Beverage',
    servingSize: 350,
    servingUnit: 'ml',
    alternateServings: [{ label: '1 smoothie', multiplier: 1 }],
    nutrition: { calories: 270, protein: 28, carbs: 35, fats: 3, fiber: 3, sugar: 20, sodium: 180, saturatedFat: 0.5 },
    isVerified: true,
  },
]

async function seedFoods() {
  try {
    console.log('Connecting to MongoDB...')
    await mongoose.connect(MONGODB_URI)
    console.log('Connected.')

    // Clear existing system foods (where createdBy is null/undefined)
    console.log('Clearing existing system foods...')
    const deleteResult = await FoodItem.deleteMany({ createdBy: { $exists: false } })
    console.log(`Removed ${deleteResult.deletedCount} existing system foods.`)

    // Also clear foods where createdBy is explicitly null
    const deleteResult2 = await FoodItem.deleteMany({ createdBy: null })
    if (deleteResult2.deletedCount > 0) {
      console.log(`Removed ${deleteResult2.deletedCount} additional system foods (createdBy: null).`)
    }

    // Insert all foods
    console.log(`Inserting ${foods.length} foods...`)
    const result = await FoodItem.insertMany(foods)
    console.log(`Successfully inserted ${result.length} food items.`)

    // Log category breakdown
    const categories: Record<string, number> = {}
    for (const food of foods) {
      categories[food.category] = (categories[food.category] || 0) + 1
    }
    console.log('\nCategory breakdown:')
    for (const [cat, count] of Object.entries(categories).sort()) {
      console.log(`  ${cat}: ${count}`)
    }

    console.log('\nFood seed complete.')
    process.exit(0)
  } catch (error) {
    console.error('Seeding error:', error)
    process.exit(1)
  }
}

seedFoods()
