/**
 * ONE place native uploads an image (NP-059).
 *
 * The web posts `multipart/form-data` with a `File` cut from the resized blob
 * (`webapp/components/nutrition/EvidencePhotoPicker.tsx`,
 * `SnapPlateModal.tsx`, `components/meals/MealForm.tsx`). React Native has no
 * `File` and no `Blob` worth sending: its `FormData` takes
 * `{ uri, name, type }` and streams the file off disk itself, which is the
 * whole reason this helper exists rather than every screen hand-rolling it.
 *
 * It goes through the SHARED CLIENT's `raw` call, not a bare `fetch`, so an
 * upload carries the same `Authorization: Bearer …` and the same `tz` handling
 * as every other native request — `createApiClient` passes a `FormData` body
 * through untouched and leaves `Content-Type` unset, which is required: the
 * boundary is generated by the networking layer and a hand-set header would
 * break the parse on the server.
 *
 * What comes back is the SAME same-origin URL the web gets — `/api/blob/<key>`
 * for the scan and food-flag routes — which is a per-member object behind the
 * session. Render it with `components/media/AuthedImage.tsx`; a plain
 * `<Image source={{ uri }}>` has no Bearer header and gets a 404.
 */

import { ApiError, createApiClient, type ApiClient } from "@become/api-client";
import { WEBAPP_BASE_URL } from "@/lib/config";
import { sessionStore, type TokenStore } from "@/lib/auth/secureStoreToken";
import { reportRequestError } from "@/lib/auth/unauthorized";
import { CAPTURE_FILE_NAME, CAPTURE_MIME_TYPE } from "@/lib/media/capture";

/** Plate-scan photo → `scans/<userId>/…`. Multipart field `file`. */
export const SCAN_IMAGE_PATH = "/api/nutrition/scans/image";

/** Food-report label photo → `food-flags/<userId>/…`. Multipart field `file`. */
export const FOOD_FLAG_IMAGE_PATH = "/api/nutrition/flags/image";

/** A meal's photo. Multipart field `image` — see `uploadMealImage`. */
export function mealImagePath(mealId: string): string {
  return `/api/meals/${encodeURIComponent(mealId)}/image`;
}

/** The field name the blob upload routes read (`form.get('file')`). */
export const BLOB_UPLOAD_FIELD = "file";

/** The field name the meal image route reads (`form.get('image')`). */
export const MEAL_UPLOAD_FIELD = "image";

/** What React Native's FormData accepts as a file part. */
export interface MultipartFile {
  uri: string;
  name: string;
  type: string;
}

/** The sliver of FormData this module uses, so a test can record the parts. */
export interface FormDataLike {
  append(name: string, value: unknown): void;
}

export interface UploadableImage {
  uri: string;
  /** Defaults to `photo.jpg`. */
  fileName?: string;
  /** Defaults to `image/jpeg` — every route allow-lists it. */
  mimeType?: string;
}

export type UploadResult =
  | { status: "uploaded"; imageUrl: string }
  /** No session on the device. Nothing was sent. */
  | { status: "signed-out" }
  | { status: "failed"; httpStatus?: number; message: string };

export interface UploadDeps {
  /** Injected whole in tests. Built from the stored session otherwise. */
  client?: ApiClient;
  /** Where the session JWT lives. Defaults to `sessionStore`. */
  store?: TokenStore;
  baseUrl?: string;
  fetchImpl?: typeof fetch;
  /** Defaults to the platform `FormData`. */
  createFormData?: () => FormDataLike;
}

export interface UploadImageInput {
  /** A Become API path, e.g. `SCAN_IMAGE_PATH`. */
  path: string;
  image: UploadableImage;
  /** Multipart field name. Defaults to `file`. */
  field?: string;
  deps?: UploadDeps;
}

const FAILED_MESSAGE = "Become could not upload that photo. Try again.";

/** The `{ uri, name, type }` part React Native streams off disk. */
export function multipartFileFor(image: UploadableImage): MultipartFile {
  return {
    uri: image.uri,
    name: image.fileName ?? CAPTURE_FILE_NAME,
    type: image.mimeType ?? CAPTURE_MIME_TYPE,
  };
}

/**
 * The URL an upload route answers with. `scans` and `food-flags` return
 * `imageUrl`; the meal route returns `{ success, imageUrl }`. Anything else is
 * treated as a failure rather than guessed at.
 */
export function imageUrlFrom(body: unknown): string | null {
  if (body === null || typeof body !== "object") return null;
  const url = (body as { imageUrl?: unknown }).imageUrl;
  return typeof url === "string" && url.length > 0 ? url : null;
}

/**
 * Upload one image. Resolves — never rejects — with what happened. A 401 is
 * reported to the ONE unauthorized handler on the way past, exactly as a
 * schema'd call would be, so an ended session ends the session here too.
 */
export async function uploadImage(
  input: UploadImageInput,
): Promise<UploadResult> {
  const deps = input.deps ?? {};
  const field = input.field ?? BLOB_UPLOAD_FIELD;

  let client = deps.client ?? null;
  if (!client) {
    const store = deps.store ?? sessionStore;
    let token: string | null = null;
    try {
      token = await store.get();
    } catch {
      token = null;
    }
    if (!token) return { status: "signed-out" };
    client = createApiClient({
      baseUrl: deps.baseUrl ?? WEBAPP_BASE_URL,
      getToken: () => token ?? undefined,
      ...(deps.fetchImpl ? { fetchImpl: deps.fetchImpl } : {}),
    });
  }

  const form = deps.createFormData ? deps.createFormData() : new FormData();
  form.append(field, multipartFileFor(input.image));

  let response: Response;
  try {
    // No `Content-Type`: the boundary belongs to the networking layer.
    response = await client.raw(input.path, { method: "POST", body: form });
  } catch {
    return { status: "failed", message: FAILED_MESSAGE };
  }

  let body: unknown = null;
  try {
    const text = await response.text();
    body = text.length > 0 ? JSON.parse(text) : null;
  } catch {
    body = null;
  }

  if (!response.ok) {
    if (response.status === 401) {
      reportRequestError(new ApiError(401, body));
    }
    const message =
      (body as { error?: unknown } | null)?.error &&
      typeof (body as { error?: unknown }).error === "string"
        ? ((body as { error: string }).error)
        : FAILED_MESSAGE;
    return { status: "failed", httpStatus: response.status, message };
  }

  const imageUrl = imageUrlFrom(body);
  if (!imageUrl) return { status: "failed", message: FAILED_MESSAGE };
  return { status: "uploaded", imageUrl };
}

/** A plate-scan photo. `scans/<userId>/…`, behind the session. */
export function uploadScanImage(
  image: UploadableImage,
  deps?: UploadDeps,
): Promise<UploadResult> {
  return uploadImage({
    path: SCAN_IMAGE_PATH,
    image,
    ...(deps ? { deps } : {}),
  });
}

/** A food report's label photo. `food-flags/<userId>/…`, behind the session. */
export function uploadFoodFlagImage(
  image: UploadableImage,
  deps?: UploadDeps,
): Promise<UploadResult> {
  return uploadImage({
    path: FOOD_FLAG_IMAGE_PATH,
    image,
    ...(deps ? { deps } : {}),
  });
}

/** A meal's photo. Different route, different field name, same helper. */
export function uploadMealImage(
  mealId: string,
  image: UploadableImage,
  deps?: UploadDeps,
): Promise<UploadResult> {
  return uploadImage({
    path: mealImagePath(mealId),
    image,
    field: MEAL_UPLOAD_FIELD,
    ...(deps ? { deps } : {}),
  });
}
