import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests/e2e',
  timeout: 120_000,
  retries: 1,
  workers: 1,
  reporter: [['list'], ['html', { outputFolder: '../playwright-report', open: 'never' }]],
  use: {
    baseURL: process.env.PLAYWRIGHT_BASE_URL || 'https://become.redbtn.io',
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    ignoreHTTPSErrors: true,
    actionTimeout: 20_000,
    navigationTimeout: 30_000,
  },
  projects: [
    {
      name: 'tutgate',
      testMatch: '**/checkin-tutorial-gate.spec.ts',
      timeout: 120_000,
      use: { ...devices['Desktop Chrome'], viewport: { width: 390, height: 844 }, video: 'off', trace: 'off', screenshot: 'only-on-failure' },
    },
    {
      name: 'nudge',
      testMatch: '**/nudge-visibility.spec.ts',
      timeout: 120_000,
      use: { ...devices['Desktop Chrome'], viewport: { width: 390, height: 844 }, video: 'off', trace: 'off', screenshot: 'off' },
    },
    {
      name: 'swap-collapse',
      testMatch: '**/swap-collapse.spec.ts',
      timeout: 180_000,
      use: { ...devices['Desktop Chrome'], viewport: { width: 390, height: 844 }, video: 'off', trace: 'off', screenshot: 'only-on-failure' },
    },
    {
      name: 'calendar-audit',
      testMatch: '**/calendar-audit.spec.ts',
      timeout: 180_000,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 390, height: 844 },
        video: 'off', trace: 'off', screenshot: 'only-on-failure',
      },
    },
    {
      name: 'estimate-barcode',
      testMatch: '**/estimate-barcode.spec.ts',
      timeout: 240_000,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 390, height: 844 },
        video: 'off', trace: 'off', screenshot: 'only-on-failure',
      },
    },
    {
      name: 'estimate-barcode',
      testMatch: '**/estimate-barcode.spec.ts',
      timeout: 240_000,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 390, height: 844 },
        video: 'off',
        trace: 'off',
        screenshot: 'only-on-failure',
      },
    },
    {
      name: 'exercise-prs-persisted',
      testMatch: '**/exercise-prs-persisted.spec.ts',
      timeout: 60_000,
      use: { ...devices['Desktop Chrome'], video: 'off' },
    },
    {
      name: 'quick-session-abandon-save',
      testMatch: '**/quick-session-abandon-save.spec.ts',
      timeout: 60_000,
      use: { ...devices['Desktop Chrome'], viewport: { width: 390, height: 844 }, video: 'off' },
    },
    {
      name: 'swap-mobile',
      testMatch: '**/swap-debug.spec.ts',
      timeout: 120_000,
      use: {
        ...devices['Pixel 7'],
        video: 'off',
        trace: 'retain-on-failure',
        screenshot: 'only-on-failure',
      },
    },
    {
      name: 'live-workout',
      testMatch: '**/live-workout-completability.spec.ts',
      timeout: 300_000,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
        video: 'off',
        trace: 'retain-on-failure',
        screenshot: 'only-on-failure',
      },
    },
    {
      name: 'onboarding-macros',
      testMatch: '**/onboarding-macros.spec.ts',
      timeout: 180_000,
      fullyParallel: false,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 390, height: 844 },
        video: 'off',
        trace: 'retain-on-failure',
        screenshot: 'only-on-failure',
      },
    },
    {
      name: 'onboarding-audit',
      testMatch: '**/onboarding-audit.spec.ts',
      timeout: 180_000,
      // Tests share one e2e user and run in sequence — the goals-page check
      // asserts on what the wizard persisted.
      fullyParallel: false,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 390, height: 844 },
        video: 'off',
        trace: 'retain-on-failure',
        screenshot: 'only-on-failure',
      },
    },
    {
      name: 'new-user-journey',
      testMatch: '**/new-user-journey.spec.ts',
      timeout: 300_000,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 390, height: 844 },
        video: 'off',
        trace: 'retain-on-failure',
        screenshot: 'only-on-failure',
      },
    },
    {
      name: 'app-shots',
      testMatch: '**/app-shots.spec.ts',
      use: { ...devices['Pixel 5'], video: 'off' },
    },
    {
      name: 'nutri-shots',
      testMatch: '**/nutri-shots.spec.ts',
      use: { ...devices['Pixel 5'], video: 'off' },
    },
    {
      name: 'serving-units-audit',
      testMatch: '**/serving-units-audit.spec.ts',
      timeout: 240_000,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 390, height: 844 },
        video: 'off',
        trace: 'off',
        screenshot: 'off',
      },
    },
    {
      name: 'serving-bug',
      testMatch: '**/serving-bug-repro.spec.ts',
      timeout: 200_000,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 390, height: 844 },
        video: 'off',
        trace: 'retain-on-failure',
        screenshot: 'only-on-failure',
      },
    },
    {
      name: 'nutrition',
      testMatch: '**/nutrition.spec.ts',
      timeout: 180_000,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 390, height: 844 },
        video: 'off',
        trace: 'retain-on-failure',
        screenshot: 'only-on-failure',
      },
    },
    {
      name: 'barcode',
      testMatch: '**/barcode.spec.ts',
      timeout: 180_000,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 390, height: 844 },
        video: 'off',
        trace: 'retain-on-failure',
        screenshot: 'only-on-failure',
      },
    },
    {
      name: 'admin-food-detail-scaling',
      testMatch: '**/admin-food-detail-scaling.spec.ts',
      timeout: 120_000,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
        video: 'off',
        trace: 'retain-on-failure',
        screenshot: 'only-on-failure',
      },
    },
    {
      name: 'calendar',
      testMatch: '**/calendar.spec.ts',
      timeout: 180_000,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 390, height: 844 },
        video: 'off',
        trace: 'retain-on-failure',
        screenshot: 'only-on-failure',
      },
    },
    {
      name: 'schedule-sync',
      testMatch: '**/schedule-sync.spec.ts',
      timeout: 120_000,
      use: {
        ...devices['Desktop Chrome'],
        video: 'off',
        trace: 'retain-on-failure',
        screenshot: 'only-on-failure',
      },
    },
    {
      name: 'nutrition-picker',
      testMatch: '**/nutrition-picker.spec.ts',
      timeout: 120_000,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 390, height: 844 },
        video: 'off',
        trace: 'retain-on-failure',
        screenshot: 'only-on-failure',
      },
    },
    {
      name: 'keyboard-inset',
      testMatch: '**/keyboard-inset.spec.ts',
      timeout: 120_000,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 390, height: 844 },
        video: 'off',
        trace: 'retain-on-failure',
        screenshot: 'only-on-failure',
      },
    },
    {
      name: 'mind-audit',
      testMatch: '**/mind-session-audit.spec.ts',
      timeout: 180_000,
      retries: 0,
      use: { ...devices['Desktop Chrome'], viewport: { width: 390, height: 844 }, video: 'off', trace: 'off' },
    },
    {
      name: 'search-overview',
      testMatch: '**/search-overview.spec.ts',
      timeout: 120_000,
      retries: 0,
      use: { ...devices['Desktop Chrome'], viewport: { width: 390, height: 844 }, video: 'off', trace: 'off' },
    },
    {
      name: 'plan-meals-cta',
      testMatch: '**/plan-meals-cta.spec.ts',
      timeout: 120_000,
      retries: 0,
      use: { ...devices['Desktop Chrome'], viewport: { width: 390, height: 844 }, video: 'off', trace: 'off' },
    },
    {
      name: 'meal-combine',
      testMatch: '**/meal-combine.spec.ts',
      timeout: 120_000,
      use: { ...devices['Desktop Chrome'], viewport: { width: 390, height: 844 }, video: 'off', trace: 'off' },
    },
    {
      name: 'meal-multiselect',
      testMatch: '**/meal-multiselect.spec.ts',
      timeout: 120_000,
      use: { ...devices['Desktop Chrome'], viewport: { width: 390, height: 844 }, video: 'off', trace: 'off' },
    },
    {
      name: 'nutrition-regression',
      testMatch: '**/nutrition-regression.spec.ts',
      timeout: 120_000,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 390, height: 844 },
        video: 'off',
        trace: 'retain-on-failure',
        screenshot: 'only-on-failure',
      },
    },
    {
      name: 'becoming-journey',
      testMatch: '**/becoming-journey.spec.ts',
      timeout: 180_000,
      use: { ...devices['Desktop Chrome'], viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, video: 'off', trace: 'retain-on-failure', screenshot: 'only-on-failure' },
    },
    {
      name: 'goals',
      testMatch: '**/goals.spec.ts',
      timeout: 120_000,
      use: { ...devices['Desktop Chrome'], viewport: { width: 390, height: 844 }, video: 'off', trace: 'retain-on-failure', screenshot: 'only-on-failure' },
    },
    {
      name: 'admin-streaks',
      testMatch: '**/admin-streaks.spec.ts',
      timeout: 120_000,
      use: { ...devices['Desktop Chrome'], video: 'off', trace: 'retain-on-failure', screenshot: 'only-on-failure' },
    },
    {
      name: 'dashboard-fixes',
      testMatch: '**/dashboard-fixes.spec.ts',
      timeout: 120_000,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 390, height: 844 },
        video: 'off',
        trace: 'retain-on-failure',
        screenshot: 'only-on-failure',
      },
    },
  ],
});
