// ── A COPY. DO NOT EDIT THIS FILE. ─────────────────────────────────────────
//
// Source: webapp/lib/workoutUtils.ts
//
// NP-058 applying NP-017: the training, streak and dashboard logic is pure,
// so both apps run the SAME code instead of two implementations of it. A
// behaviour change lands on the WEB first and is re-copied here, and
// webapp/tests/unit/nativeParity/trainingModules.test.ts runs this copy
// against the web source over a fixture table and fails until it is.
// Re-copy procedure: expo/README.md, "Re-copying a training module".
//
// The only edits a copy may carry:
//  * imports rewritten to relative paths, and the webapp model/store types
//    they were type-only imports of mirrored in ../types.ts;
//  * the non-null assertions `noUncheckedIndexedAccess` asks for (set by
//    expo/tsconfig.json, which typechecks these sources; webapp does not
//    set it). Assertions only — no runtime branch is added or removed.
// ──────────────────────────────────────────────────────────────────────────
// Shared workout exercise grouping and flow utilities

export interface WorkoutExercise {
  exerciseSlug?: string;
  name: string;
  type?: string;
  trackingType?: string;      // reps_weight | reps_bodyweight | reps_only | time | time_distance | intervals | none
  sets?: number;
  reps?: string;              // rep target (or interval target: "20 cal", "AMRAP")
  rest?: string;
  tempo?: string;             // e.g. "3-1-1-0"
  rpe?: number;               // 1-10
  duration?: string;          // timed prescription: "30 sec", "60 sec"
  details?: string;           // coach notes for this exercise in this program
  tip?: string;               // quick cue shown during live workout
  videoUrl?: string;
  thumbnailUrl?: string;
  primaryMuscles?: string[];  // hydrated from exercise DB
  difficulty?: string;        // hydrated from exercise DB
  equipment?: string[];       // hydrated from exercise DB — drives per-DB/KB weight logging
  laterality?: string;        // hydrated from exercise DB
  movementPatterns?: string[]; // hydrated from exercise DB
  groupId?: string;
  groupType?: string;
  groupLabel?: string;
  groupRest?: string;
  groupRounds?: number;
}

export interface ExerciseGroup {
  groupId: string | null;
  groupType?: string;
  groupLabel?: string;
  groupRest?: string;
  groupRounds?: number;
  exercises: { exercise: WorkoutExercise; originalIndex: number }[];
}

/**
 * Group consecutive exercises that share the same groupId.
 * Ungrouped exercises each get their own single-exercise group.
 */
export function groupExercises(exercises: WorkoutExercise[]): ExerciseGroup[] {
  const groups: ExerciseGroup[] = [];
  let i = 0;

  while (i < exercises.length) {
    const ex = exercises[i]!;
    if (ex.groupId) {
      const group: ExerciseGroup = {
        groupId: ex.groupId,
        groupType: ex.groupType,
        groupLabel: ex.groupLabel,
        groupRest: ex.groupRest,
        groupRounds: ex.groupRounds,
        exercises: [],
      };
      while (i < exercises.length && exercises[i]!.groupId === ex.groupId) {
        group.exercises.push({ exercise: exercises[i]!, originalIndex: i });
        i++;
      }
      groups.push(group);
    } else {
      groups.push({
        groupId: null,
        exercises: [{ exercise: ex, originalIndex: i }],
      });
      i++;
    }
  }
  return groups;
}

/**
 * A single step in the live workout flow.
 */
export interface WorkoutStep {
  exerciseIndex: number;   // index into the flat exercises array
  setIndex: number;        // which set (0-based)
  groupId: string | null;  // null for ungrouped
  isLastInRound: boolean;  // true if last exercise in a superset round
  isFirstInRound: boolean; // true if first exercise in a superset round
  roundNumber: number;     // which round (0-based)
}

/**
 * Build a step-based flow for the live workout.
 * - Ungrouped exercises: sequential steps through all sets
 * - Grouped exercises (supersets/circuits): interleaved
 *   A-set1 → B-set1 → A-set2 → B-set2 → ...
 */
export function buildWorkoutFlow(exercises: WorkoutExercise[]): WorkoutStep[] {
  const groups = groupExercises(exercises);
  const steps: WorkoutStep[] = [];

  for (const group of groups) {
    if (group.groupId === null || group.exercises.length <= 1) {
      // Ungrouped: sequential sets
      const { exercise, originalIndex } = group.exercises[0]!;
      const numSets = exercise.sets || 3;
      for (let s = 0; s < numSets; s++) {
        steps.push({
          exerciseIndex: originalIndex,
          setIndex: s,
          groupId: null,
          isLastInRound: true,
          isFirstInRound: true,
          roundNumber: s,
        });
      }
    } else {
      // Grouped: interleave exercises per round
      const maxSets = Math.max(
        group.groupRounds || 0,
        ...group.exercises.map(({ exercise }) => exercise.sets || 3)
      );
      for (let round = 0; round < maxSets; round++) {
        for (let exI = 0; exI < group.exercises.length; exI++) {
          const { exercise, originalIndex } = group.exercises[exI]!;
          const numSets = exercise.sets || 3;
          if (round < numSets) {
            steps.push({
              exerciseIndex: originalIndex,
              setIndex: round,
              groupId: group.groupId,
              isFirstInRound: exI === 0,
              isLastInRound: exI === group.exercises.length - 1,
              roundNumber: round,
            });
          }
        }
      }
    }
  }

  return steps;
}
